Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-02, with the labels that each got.

#809 mycrypto.com
  src/config.json
Labels: whitelist request

#810 adhive.net & tokensale.adhive.net
  src/config.json
Labels: blacklist request

#817 zacrypto.info + more false positives
  src/config.json
Labels: whitelist request

#819 jkcrypto.com
  src/config.json
Labels: whitelist request

#820 trx.foundation
  src/config.json
Labels: blacklist request

#822 mycrypto.ninja
  src/config.json
Labels: whitelist request

#825 crypto.me
  src/config.json
Labels: whitelist request

#827 crypto.review
  src/config.json
Labels: whitelist request

#829 cryptojobslist.com
  src/config.json
Labels: whitelist request

#834 ucrypto.com + more false-positives
  src/config.json
Labels: whitelist request

#846 crypto.jobs
  src/config.json
Labels: whitelist request

#847 crypto.bi + others
  src/config.json
Labels: whitelist request

#842 originprotocol.io
  src/config.json
Labels: blacklist request

#843 bankera.live
  src/config.json
Labels: blacklist request

#849 sale-earn.com
  src/config.json
Labels: blacklist request

#850 myetherwallet.custom-token.com
  src/config.json
Labels: blacklist request

#851 mycrypto.dk
  src/config.json
Labels: whitelist request

#853 scrypto.io
  src/config.json
Labels: whitelist request

#854 xn--yethewalle-to2exkhi.com
  src/config.json
Labels: blacklist request

#859 mycrypto.ca & acrypto.io
  src/config.json
Labels: whitelist request

#861 mycrypto24.online
  src/config.json
Labels: whitelist request

#862 Whitelist crypto.bg
  src/config.json
Labels: whitelist request

#864 zzcrypto.net & zzcrypto.org
  src/config.json
Labels: whitelist request

#866 melcrypto.com
  src/config.json
Labels: whitelist request

#868 spcrypto.net
  src/config.json
Labels: whitelist request

#869 remme.live
  src/config.json
Labels: blacklist request

#870 myeterhwaliot.com xn--myeerhwailet-ooc.com nyeitthervvallet.com
  src/config.json
Labels: blacklist request

#872 ohmycrypto.io
  src/config.json
Labels: whitelist request

#874 crypto.kred
  src/config.json
Labels: whitelist request

#879 iccrypto.io & wecrypto.net
  src/config.json
Labels: whitelist request

#875 remme.in
  src/config.json
Labels: blacklist request

#881 ethexploit.org
  src/config.json
Labels: blacklist request

#882 xn--mycrypt-r0a.com xn--mycrypt-g1a.com xn--mycrpto-y2a.com
  src/config.json
Labels: blacklist request

#883 dock.promo & dock.so
  src/config.json
Labels: blacklist request

#884 jibreltoken.in
  src/config.json
Labels: blacklist request, whitelist request

#885 nucleus-vision.cc + more
  src/config.json
Labels: blacklist request

#886 xn--myetheralle-7b9ezl.com + xn--myethrwalle-jb9e19a.com
  src/config.json
Labels: blacklist request

#888 crypto.pro
  src/config.json
Labels: whitelist request

#890 icotoken-current.top
  src/config.json
Labels: blacklist request

#891 vechain-foundation.com + more
  src/config.json
Labels: blacklist request

#892 openplatform.tech
  src/config.json
Labels: blacklist request

#895 crypto.tickets
  src/config.json
Labels: whitelist request

#897 mycrypter.com
  src/config.json
Labels: whitelist request

#900 fake dock crowdsale sites
  src/config.json
Labels: blacklist request

#901 xn--es-8bb.com xn--myetherallt-pl9elw.com + more
  src/config.json
Labels: blacklist request

#902 fin-trux.com + more
  src/config.json
Labels: blacklist request

#903 xn--polonx-0va26t.com
  src/config.json
Labels: blacklist request

#905 jiocoins.io
  src/config.json
Labels: blacklist request

#910 mmcrypto.io
  src/config.json
Labels: whitelist request

#912 zycrypto.com
  src/config.json
Labels: whitelist request

#913 crypto.nl
  src/config.json
Labels: whitelist request

#906 add seele ico scam domains
  src/config.json
  src/hosts.txt
Labels: blacklist request

#915 hicrypto.io
  src/config.json
Labels: whitelist request

#916 xn--binnce-5nf.com xn--biace-4l1bb.com
  src/config.json
Labels: blacklist request

#917 syncfab ico scam
  src/config.json
  src/hosts.txt
Labels: blacklist request

#919 forkdeita.github.io
  src/config.json
Labels: blacklist request

#920 ton.fund
  src/config.json
Labels: blacklist request

#923 becrypto.xyz
  src/config.json
Labels: whitelist request

#925 polyswarm.bid polyswarm.co
  src/config.json
Labels: blacklist request

#926 crypto.press
  src/config.json
Labels: whitelist request

#928 sale-dock.com
  src/config.json
Labels: blacklist request

#930 mqtcrypto.com
  src/config.json
Labels: whitelist request

#931 polyswarm.in
  src/config.json
Labels: blacklist request

#932 seele-token.pro + more
  src/config.json
Labels: blacklist request

#935 dock.network
  src/config.json
Labels: blacklist request

#937 dock-io.org
  src/config.json
Labels: blacklist request

#940 polyswarm.pw
  src/config.json
Labels: blacklist request

#941 dock-tokensale.eu
  src/config.json
Labels: blacklist request

#942 polyswarm.ru polyswarm.tech
  src/config.json
Labels: blacklist request

#943 dflnlty.org
  src/config.json
Labels: blacklist request

#944 a scam dfinity site
  src/hosts.txt
Labels: blacklist request

#945 tron-foundation.org + more
  src/config.json
Labels: blacklist request

#946 xn--yeterwallet-bm8eym.com
  src/config.json
Labels: blacklist request

#948 why "myethlerwallet.com" is part of whitelist?
  src/config.json
Labels: blacklist request

#952 cryptocities.world rucrypto.com cryptokittens.club
  src/config.json
Labels: whitelist request

#954 netmask.hu
  src/config.json
Labels: whitelist request

#956 9crypto.co
  src/config.json
Labels: whitelist request

#957 el-petro-coin.com
  src/config.json
Labels: blacklist request

#958 xn--myethewalle-w48erh.com myetherwallett.site
  src/config.json
Labels: blacklist request

#963 ncrypto.tech
  src/config.json
Labels: whitelist request

#968 mywalletether.com
  src/config.json
Labels: blacklist request

#969 tefood.me + more
  src/config.json
Labels: blacklist request

#982 add coindesk and myetherwallet variants
  src/config.json
Labels: blacklist request

#996 mpcrypo.com
  src/config.json
Labels: whitelist request

#997 address-transfer-confirmation.droppages.com
  src/config.json
Labels: blacklist request

#998 akasha-world.com
  src/config.json
Labels: blacklist request

#999 6khb.payment-checker-ethereum-id-bslyftexjuwcgv8.filesusr.com
  src/config.json
Labels: blacklist request

#1001 neonexchanges.org
  src/config.json
Labels: blacklist request

#1002 gonetwork-airdrop.co
  src/config.json
Labels: blacklist request

#1006 add ton-sale.com to the blacklist
  src/config.json
Labels: blacklist request

#1011 telegram.tokyo
  src/hosts.txt
Labels: blacklist request

#1012 forkdelta.io & telegram.tokyo
  src/config.json
Labels: blacklist request

#1014 vechain-foundation.org + more
  src/config.json
Labels: blacklist request

#1015 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1016 dfinlty.org
  src/config.json
Labels: blacklist request

#1017 transfer-address-confirmation.droppages.com + more
  src/config.json
Labels: blacklist request

#1018 add hawen[.]io and havven[.]xyz
  src/config.json
Labels: blacklist request

#1022 tokensale-adhive.com
  src/config.json
Labels: blacklist request

#1023 ipsx.promo
  src/config.json
Labels: blacklist request

#1024 dflinity.org
  src/config.json
Labels: blacklist request

#1025 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1026 xn--coindek-873c.com + more
  src/config.json
Labels: blacklist request

#1028 mycrypto.website
  src/config.json
Labels: whitelist request

#1030 ggcrypto.net
  src/config.json
Labels: whitelist request

#1033 Add tomo-coin.io phishing site
  src/config.json
Labels: blacklist request

#1034 Report phishing site tomo-coin.io
  src/hosts.txt
Labels: blacklist request

#1038 tron-online.org + more
  src/config.json
Labels: blacklist request

#1039 meganfoxloveyou.com + more
  src/config.json
Labels: blacklist request

#1041 nucelus.vision
  src/config.json
Labels: blacklist request

#1043 havvenio.com
  src/config.json
Labels: blacklist request

#1045 xn--havvn-9za.io
  src/config.json
Labels: blacklist request
