Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-08, with the labels that each got.

#2193 Update domains with iosiro.com
  src/config.json
Labels: blacklist request

#2194 Update with iosiro.com blacklist
  src/config.json
Labels: blacklist request

#2195 clubeth.live + more
  src/config.json
Labels: blacklist request

#2197 kraken-ixz.com + more
  src/config.json
Labels: blacklist request

#2198 ethereum-promotion.org + more
  src/config.json
Labels: blacklist request

#2199 update with iosiro.com
  src/config.json
Labels: blacklist request

#2200 aronum.com + more
  src/config.json
Labels: blacklist request

#2203 Update with iosiro.com
  src/config.json
Labels: blacklist request

#2204 xn--etereum-yt3c.com
  src/config.json
Labels: blacklist request

#2206 Update with iosiro.com
  src/config.json
Labels: blacklist request

#2207 mfoundation.cf
  src/config.json
Labels: blacklist request

#2208 bigethereum.org + more
  src/config.json
Labels: blacklist request

#2210 medeum-airdrop-news.com + ethereum-transfer.net
  src/config.json
Labels: blacklist request

#2219 forkdelta.biz + more
  src/config.json
Labels: blacklist request

#2220 bjlttrex.com + more
  src/config.json
Labels: blacklist request

#2221 safeclaims.space + more
  src/config.json
Labels: blacklist request

#2223 Update with iosiro.com
  src/config.json
Labels: blacklist request

#2224 metacash.online + metacash.it
  src/config.json
Labels: whitelist request

#2226 bliovnarnce.com + more
  src/config.json
Labels: blacklist request

#2230 binancepromos.typeform.com/to/ZRE0mt
  src/config.json
Labels: blacklist request

#2231 Update from iosiro.com
  src/config.json
Labels: blacklist request

#2232 airdropbox.site + more
  src/config.json
Labels: blacklist request

#2233 xn--bnanc-r51bze.com + more
  src/config.json
Labels: blacklist request

#2235 Update from iosiro.com
  src/config.json
Labels: blacklist request

#2237 Update from iosiro.com
  src/config.json
Labels: blacklist request

#2238 kralkem.com + more
  src/config.json
Labels: blacklist request

#2240 ethcoin.store
  src/config.json
Labels: blacklist request

#2241 Update from iosiro.com
  src/config.json
Labels: blacklist request

#2242 xn--omiseg-ul8b.com + more
  src/config.json
Labels: blacklist request

#2246 Update from iosiro.com
  src/config.json
Labels: blacklist request

#2247 drcrypto.net
  src/config.json
Labels: whitelist request

#2248 cbase-pro.com + more
  src/config.json
Labels: blacklist request

#2249 binance.com.eth-bonus.me + more
  src/config.json
Labels: blacklist request

#2251 myehtervvalliet.com + more
  src/config.json
Labels: blacklist request

#2252 update with iosiro.com blacklist
  src/config.json
Labels: blacklist request

#2254 nectracker.co + more
  src/config.json
Labels: blacklist request

#2255 accounts-blockchain.info + more
  src/config.json
Labels: blacklist request

#2256 safe.justgeteth.com + more
  src/config.json
Labels: blacklist request

#2257 bittrex-sigin.com
  src/config.json
Labels: blacklist request

#2261 eth-club.club + more
  src/config.json
Labels: blacklist request

#2267 musk-air.org + more
  src/config.json
Labels: blacklist request

#2268 ethgetbonus.eu + more
  src/config.json
Labels: blacklist request

#2270 bestchagne.com + more
  src/config.json
Labels: blacklist request

#2272 eth-secure.top + more
  src/config.json
Labels: blacklist request

#2273 walletverify.info + more
  src/config.json
Labels: blacklist request

#2274 whitelist acatus.com
  src/config.json
Labels: whitelist request

#2275 myetheatrwallet.com + more
  src/config.json
Labels: blacklist request

#2276 ethtw.info + more
  src/config.json
Labels: blacklist request

#2277 ethpromogiving.com + more
  src/config.json
Labels: blacklist request

#2279 verify.10000eth.pro + more
  src/config.json
Labels: blacklist request

#2281 coinbase.tx-pr0.com + more
  src/config.json
Labels: blacklist request

#2283 Changed MEW endpoints #2280
  src/config.json
  test/index.js
Labels: enhancement

#2282 ethereum-foundation.info + more
  src/config.json
Labels: blacklist request

#2286 eth-claim.pw + more
  src/config.json
Labels: blacklist request

#2287 hitbtc1.website + more
  src/config.json
Labels: blacklist request

#2290 ethereum-bonus.biz + more
  src/config.json
Labels: blacklist request

#2291 idexmark.online + eth-gifting.com
  src/config.json
Labels: blacklist request

#2292 autos.ca + aicrypto.io + etherkan.com
  src/config.json
Labels: whitelist request

#2295 Update with iosiro.com
  src/config.json
Labels: blacklist request

#2296 google.com.tokensale.ws
  src/config.json
Labels: blacklist request

#2300 binanblog.blogspot.com + more
  src/config.json
Labels: blacklist request

#2301 biltmex.com + more
  src/config.json
Labels: blacklist request

#2304 bitmex-in.co + more
  src/config.json
Labels: blacklist request

#2305 cryptokitties.city
  src/config.json
Labels: whitelist request

#2306 lbitmex-in.com + myetalonwindow.info
  src/config.json
Labels: blacklist request

#2307 myetherwallat.club + more
  src/config.json
Labels: blacklist request

#2308 log-in-binance.com
  src/config.json
Labels: blacklist request

#2309 xn--myeherwllet-wte7564g.com + more
  src/config.json
Labels: blacklist request

#2313 binance-lgin.com + more
  src/config.json
Labels: blacklist request

#2312 Update with phishfort.com blacklist
  src/config.json
Labels: blacklist request

#2316 dmunity.com
  src/config.json
Labels: whitelist request

#2318 eth-bonus-live-binance.com + more
  src/config.json
Labels: blacklist request

#2320 blokclnain.com + more
  src/config.json
Labels: blacklist request

#2321 selleth.io
  src/config.json
Labels: blacklist request
