Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-04, with the labels that each got.

#1290 myetnarvellat.com + more
  src/config.json
Labels: blacklist request

#1291 cz-binance.com
  src/config.json
Labels: blacklist request

#1299 quantstump.com + quantstampcoin.com + quantistamp.com
  src/config.json
Labels: blacklist request

#1301 airdrop-bluzelle.com + more
  src/config.json
Labels: blacklist request

#1302 payforfees.online
  src/config.json
Labels: blacklist request

#1303 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1304 dfinity.org.in
  src/config.json
Labels: blacklist request

#1306 cryptoplus.be + more
  src/config.json
Labels: blacklist request

#1307 list of fake MEW domains
  src/config.json
Labels: blacklist request

#1309 mycrypto.company
  src/config.json
Labels: blacklist request

#1312 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1313 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1319 tron-nextlevel.bitballoon.com + more
  src/config.json
Labels: blacklist request

#1320 divinity.game + more
  src/config.json
Labels: whitelist request

#1321 ethereum-promo2018.bitballoon.com
  src/config.json
Labels: blacklist request

#1322 ethereums-promo.bitballoon.com + eth-gifting.site
  src/config.json
Labels: blacklist request

#1323 gramtokenico.com
  src/config.json
Labels: blacklist request

#1325 centratoken.site
  src/config.json
Labels: blacklist request

#1334 Scam as fuck - Tron Fundation
  src/config.json
Labels: blacklist request

#1339 check-ethpayments.kissr.com + more
  src/config.json
Labels: blacklist request

#1340 ethc.gift
  src/config.json
Labels: blacklist request

#1343 hopeful-poitras-654e5a.bitballoon.com
  src/config.json
Labels: whitelist request

#1345 tacrypto.net
  src/config.json
Labels: whitelist request

#1346 quantstamp.com & app.quantstamp.com
  src/config.json
Labels: whitelist request

#1348 free-5000eth.com
  src/config.json
Labels: blacklist request

#1351 ethhit.com + ethereumpromo.info
  src/config.json
Labels: blacklist request

#1352 trust-trading scams
  src/config.json
Labels: blacklist request

#1353 tokencrowdsale.info
  src/config.json
Labels: blacklist request

#1360 arhash.xyz + more
  src/config.json
Labels: whitelist request

#1361 eth-give-away.webz.cz + more
  src/config.json
Labels: blacklist request

#1362 ethc.fund + ethereum.czweb.org
  src/config.json
Labels: blacklist request

#1364 givingawayethereum.com
  src/config.json
Labels: blacklist request

#1365 ethereum-give.byethost16.com
  src/config.json
Labels: blacklist request

#1367 smartolinks.com livivid.com clickmoneysystem1.com + more
  src/config.json
Labels: blacklist request

#1370 ethereum-giveaway.com
  src/config.json
Labels: blacklist request

#1371 underwear-leaderboard.bitballoon.com
  src/config.json
Labels: whitelist request

#1373 givingawayeth.com
  src/config.json
Labels: blacklist request

#1375 ethereums-2018-give-away.bitballoon.com + more
  src/config.json
Labels: blacklist request

#1376 octus.network
  src/config.json
Labels: whitelist request

#1377 ethereum-giveaway.tekcities.com
  src/config.json
Labels: blacklist request

#1381 gether.fund + more
  src/config.json
Labels: blacklist request

#1382 5000eth-giveaway.online
  src/config.json
Labels: blacklist request

#1383 www-colnbase.com
  src/config.json
Labels: blacklist request

#1384 xn--conbas-gva1a.com
  src/config.json
Labels: blacklist request

#1388 eth-giving.com + more
  src/config.json
Labels: blacklist request

#1389 localetherwallet.com
  src/config.json
Labels: blacklist request

#1390 eos-dac.com
  src/config.json
Labels: blacklist request

#1393 btc-gifts.info + eth-promotion.getforge.io
  src/config.json
Labels: blacklist request

#1394 myetherwallet-register.com + myetherwallet.lt
  src/config.json
Labels: blacklist request

#1401 tokentelegram.net
  src/config.json
Labels: blacklist request

#1403 ethtotrade.com
  src/config.json
Labels: blacklist request

#1406 eth-give.org + more
  src/config.json
Labels: blacklist request

#1386 Fake originprotocol.com
  src/config.json
Labels: blacklist request

#1407 etherscan.tech
  src/config.json
Labels: blacklist request

#1410 get-ether.gift
  src/config.json
Labels: blacklist request

#1412 crypto.ch + more
  src/config.json
Labels: whitelist request

#1413 neonexchange.website
  src/config.json
Labels: blacklist request

#1415 Fake MyEtherWallets
  src/config.json
Labels: blacklist request

#1416 ethtoget.com + ethereumbonus.online
  src/config.json
Labels: blacklist request

#1417 xn--myethewllet-w48ep6a.com + xn--myetherwalle-occ.com
  src/config.json
Labels: blacklist request

#1419 get-ether.me
  src/config.json
Labels: blacklist request

#1420 nkn-token.io
  src/config.json
Labels: blacklist request

#1424 ethhit.org + more
  src/config.json
Labels: blacklist request

#1426 win-eth.org
  src/config.json
Labels: blacklist request

#1427 ethen.market
  src/config.json
Labels: whitelist request

#1428 apttus.com + kactus.io
  src/config.json
Labels: whitelist request

#1429 mithriltoken.tech
  src/config.json
Labels: blacklist request

#1430 myethverwallet.com
  src/config.json
Labels: blacklist request

#1331 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1433 dfinity.ml
  src/hosts.txt
Labels: blacklist request

#1434 dfinity.ml + aelftoken.com
  src/config.json
Labels: blacklist request

#1435 xn--myethrwalet-ns8e73d.com
  src/config.json
Labels: blacklist request

#1436 5000ethgive.com + more
  src/config.json
Labels: blacklist request

#1437 xn--mcrypto-rpd.com + more
  src/config.json
Labels: blacklist request

#1438 eth-foundation.github.io + mnyetnherwaliet.com
  src/config.json
Labels: blacklist request

#1439 ethereumpomo.online
  src/config.json
Labels: blacklist request

#1444 ethforeth.com + more
  src/config.json
Labels: blacklist request

#1446 nmyetlerwaliet.com + more
  src/config.json
Labels: blacklist request

#1445 Fake originprotocol.com
  src/config.json
Labels: blacklist request, whitelist request

#1449 gether-gift.com + poloniex-withdrawals.bitballoon.com
  src/config.json
Labels: blacklist request

#1451 ethpromoverge.com
  src/config.json
Labels: blacklist request

#1456 originprotocol.com
  src/config.json
Labels: whitelist request

#1455 add dav-network.io
  src/config.json
Labels: blacklist request

#1457 offpromoeth.com
  src/config.json
Labels: blacklist request

#1459 shapeskift.io + shapeslhift.io
  src/config.json
Labels: blacklist request

#1461 5000eth-giveaway.getforge.io + get5000eth.com
  src/config.json
Labels: blacklist request

#1462 ethgiveaway.org + more
  src/config.json
Labels: blacklist request

#1463 eth-today.rf.gd
  src/config.json
Labels: blacklist request

#1464 getyoureth.com
  src/config.json
Labels: blacklist request

#1466 nmyetlerwaiiet.com + more
  src/config.json
Labels: blacklist request

#1467 get-ethereum.cc + freecoiners.com
  src/config.json
Labels: blacklist request

#1468 add pyapay.co
  src/config.json
Labels: blacklist request

#1470 clo-airdrop.info
  src/config.json
Labels: blacklist request

#1471 myehterwallet-ht.com + more
  src/config.json
Labels: blacklist request

#1473 add daostack-token.io
  src/config.json
Labels: blacklist request

#1478 add icolist.sale/daostack/
  src/config.json
Labels: blacklist request

#1476 Whitelist "aptus.be"
  src/config.json
Labels: whitelist request

#1479 n2crypto.com + more
  src/config.json
Labels: whitelist request

#1480 gift5000-eth.com + more
  src/config.json
Labels: blacklist request

#1481 xn--mytherwalet-ms8e53d.com + more MEW idn
  src/config.json
Labels: blacklist request

#1484 gift-5000eth.com + more
  src/config.json
Labels: blacklist request

#1485 mocrypto.io
  src/config.json
Labels: whitelist request

#1486 localetherieum.com
  src/config.json
Labels: blacklist request

#1489 polymath-network.com + more
  src/config.json
Labels: blacklist request

#1490 5000eth-giveaway.com + ethereum-give.czweb.or
  src/config.json
Labels: blacklist request

#1492 get-ethereum.gift + more
  src/config.json
Labels: blacklist request

#1496 tokentelegram.info + more
  src/config.json
Labels: blacklist request

#1497 ethereums.cloud + more
  src/config.json
Labels: blacklist request

#1499 smbr.rf.gd
  src/config.json
Labels: whitelist request

#1500 quarkchain-tokensale.io
  src/config.json
Labels: blacklist request

#1501 5000ethgift.com + mvmonero.co
  src/config.json
Labels: blacklist request

#1503 mycrypto.promo + more
  src/config.json
Labels: blacklist request

#1504 gift-5000eth.org + ethpromo.net
  src/config.json
Labels: blacklist request

#1505 ethereums.live
  src/config.json
Labels: blacklist request

#1509 collecteth.com + more
  src/config.json
Labels: blacklist request

#1510 ethereumdrop.batcave.net + etherdrops.com
  src/config.json
Labels: blacklist request

#1511 sanctus.io
  src/config.json
Labels: whitelist request

#1514 ethersat.io
  src/config.json
Labels: whitelist request

#1515 geteths.live + more
  src/config.json
Labels: blacklist request

#1516 Fake/Suspect MyEtherWallet domains
  src/config.json
Labels: blacklist request

#1517 ethgiveaways.net + more
  src/config.json
Labels: blacklist request

#1519 bitfinex.eu
  src/config.json
Labels: blacklist request
