Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-06, with the labels that each got.

#1732 calchain.net + ethpays.me
  src/config.json
Labels: blacklist request

#1733 ethgive.me + more
  src/config.json
Labels: blacklist request

#1735 xn--myetherwllt-f7a75e.com
  src/config.json
Labels: blacklist request

#1738 ethpromo.io + more
  src/config.json
Labels: blacklist request

#1739 ethgw.info + more
  src/config.json
Labels: blacklist request

#1740 tron.gg + more
  src/config.json
Labels: blacklist request

#1741 saferpayether.com + more
  src/config.json
Labels: blacklist request

#1742 xn--myetherwllt-r7a44e.com + kinetictokenform.typeform.com
  src/config.json
Labels: blacklist request

#1743 myetehrewallet.com + more
  src/config.json
Labels: blacklist request

#1747 idexmarket.io
  src/config.json
Labels: blacklist request

#1748 ethofficial.info + more
  src/config.json
Labels: blacklist request

#1749 keyfund.io + more
  src/config.json
Labels: blacklist request

#1751 eos-swap.com
  src/config.json
Labels: blacklist request

#1753 ethpromo.cc + more
  src/config.json
Labels: blacklist request

#1750 Another obvious scam
  src/config.json
Labels: blacklist request

#1755 promotoeth.org
  src/config.json
Labels: blacklist request

#1758 idex-market.eu + more
  src/config.json
Labels: blacklist request

#1759 eth-get.com + more
  src/config.json
Labels: blacklist request

#1761 idek.io + more
  src/config.json
Labels: blacklist request

#1762 collect.bestethgift.com + bestethgift.com
  src/config.json
Labels: blacklist request

#1763 btcoin.vu + more
  src/config.json
Labels: blacklist request

#1764 electrocoin.typeform.com + myetherwalllet.trade
  src/config.json
Labels: blacklist request

#1765 idex-market.io + more
  src/config.json
Labels: blacklist request

#1769 telegram.vu + more
  src/config.json
Labels: blacklist request

#1770 myiteher.com + more
  src/config.json
Labels: blacklist request

#1772 etherskan.io + etherscan.ltd
  src/config.json
Labels: blacklist request

#1773 fantoms.foundation
  src/config.json
Labels: blacklist request

#1775 myetherwallat.co + more
  src/config.json
Labels: blacklist request

#1777 ethereum.website.tk + more
  src/config.json
Labels: blacklist request

#1778 get.ethpublic.com + more
  src/config.json
Labels: blacklist request

#1779 mycrypto.guru + avotus.com
  src/config.json
Labels: whitelist request

#1782 etherepromo.win + more
  src/config.json
Labels: blacklist request

#1784 myethrwatt.com + more
  src/config.json
Labels: blacklist request

#1786 zecblock.info + more
  src/config.json
Labels: blacklist request

#1787 xn--myetherwalett-4hc.net + ethereumgiveaway.typeform.com
  src/config.json
Labels: blacklist request

#1789 cryptoaway.org + more
  src/config.json
Labels: blacklist request

#1793 safe.ethxchanges.com + more
  src/config.json
Labels: blacklist request

#1797 free-ethereum.us + more
  src/config.json
Labels: blacklist request

#1799 xn--myethrwalett-8vb19c.net
  src/config.json
Labels: blacklist request

#1800 A bunch of fake MyEtherWallets
  src/config.json
Labels: blacklist request

#1803 zillowblockchain.org + more
  src/config.json
Labels: blacklist request

#1804 ether-give.club + myethertrust.com
  src/config.json
Labels: blacklist request

#1806 etheroll.io
  src/config.json
Labels: blacklist request

#1809 xn--myetherrwalet-5hc.net + more
  src/config.json
Labels: blacklist request

#1810 cactus.lu + crypto.schule
  src/config.json
Labels: whitelist request

#1813 xn--mythrwalet-smb0a15c.com + more
  src/config.json
Labels: blacklist request

#1814 xn--myetherwalle-mm5f.com + more
  src/config.json
Labels: blacklist request

#1815 kentra.tech + xn--myethrwalt-inbe64c.com
  src/config.json
Labels: blacklist request

#1818 crypto.markets + metamath.org
  src/config.json
Labels: whitelist request

#1819 putty-portal.com + arweave.pw
  src/config.json
Labels: blacklist request

#1820 bittrex-id.com
  src/config.json
Labels: blacklist request

#1821 idex-market.at + wallet-idex.net
  src/config.json
Labels: blacklist request

#1822 ethpubs.com + more
  src/config.json
Labels: blacklist request

#1823 myighther.net + eteclum.org
  src/config.json
Labels: blacklist request

#1825 idexs.market + more
  src/config.json
Labels: blacklist request

#1826 creteprint-driveways.co.uk + more
  src/config.json
Labels: blacklist request

#1827 crypto.gratis
  src/config.json
Labels: whitelist request

#1828 giveethers.info
  src/config.json
Labels: blacklist request

#1829 eth.blogmedium.top + more
  src/config.json
Labels: blacklist request

#1830 ethpromoaction.com + more
  src/config.json
Labels: blacklist request

#1834 idix-market.info + icon-block.org
  src/config.json
Labels: blacklist request

#1835 ethergive.net
  src/config.json
Labels: blacklist request

#1836 airtake.info
  src/config.json
Labels: blacklist request

#1837 Fake form for "Origin's Protocol Crowdsale"
  src/config.json
Labels: blacklist request

#1840 walleteos.io + more
  src/config.json
Labels: blacklist request

#1842 welcome.promotionaleth.com
  src/config.json
Labels: blacklist request

#1843 hederahashgraph.tokenico.me + more
  src/config.json
Labels: blacklist request

#1844 getbigdeals.org + more
  src/config.json
Labels: blacklist request

#1845 ploloneix.com + more
  src/config.json
Labels: blacklist request

#1846 xn--myethrwllt-y4a7gf.com + giveawaypromo.byethost14.com
  src/config.json
Labels: blacklist request

#1849 etherbonus.win + more
  src/config.json
Labels: blacklist request

#1850 index-markels.com
  src/config.json
Labels: blacklist request

#1851 eth-claim.org + more
  src/config.json
Labels: blacklist request

#1865 today-ethereum.com + more
  src/config.json
Labels: blacklist request

#1868 index-marketz.com + more
  src/config.json
Labels: blacklist request

#1869 ethereumgw.org + epromo.cc
  src/config.json
Labels: blacklist request

#1870 giveawaypromo.byethost14.com + more
  src/config.json
Labels: blacklist request

#1871 etherwan.com + more
  src/config.json
Labels: whitelist request

#1872 iddexmarket.com + more
  src/config.json
Labels: blacklist request

#1884 indexmarkett-corp.com + more
  src/config.json
Labels: blacklist request

#1885 ethereum-prize.com + more
  src/config.json
Labels: blacklist request

#1876 Added mycrypto.store to whitelist.
  src/config.json
Labels: whitelist request

#1880 False positive removed l2crypto.com
  src/config.json
Labels: whitelist request

#1875 removed rf.gd freehost
  src/config.json
Labels: whitelist request

#1874 removed bitballoon
  src/config.json
Labels: whitelist request

#1877 Removed geocities.ws
  src/config.json
Labels: whitelist request

#1878 Added x-crypto.com to whitelist
  src/config.json
Labels: whitelist request

#1879 Whitelisted crypto.ru
  src/config.json
Labels: whitelist request

#1886 myetherwallett.net + more
  src/config.json
Labels: blacklist request

#1887 xn--myeterwallet-o0b.com
  src/config.json
Labels: blacklist request

#1889 elon-shares.com
  src/config.json
Labels: blacklist request

#1890 s-msg-myetherwallet.com + xn--mythrwallt-fnbcf.com
  src/config.json
Labels: blacklist request

#1891 crypto.fm
  src/config.json
Labels: whitelist request

#1893 get.perfecteth.com + more
  src/config.json
Labels: blacklist request

#1908 ethereum-claim.org + more
  src/config.json
Labels: blacklist request

#1909 ethshare.org + more
  src/config.json
Labels: blacklist request

#1911 xn--coinbas-z8a.tk
  src/config.json
Labels: blacklist request

#1914 waves-platform.net + more
  src/config.json
Labels: blacklist request

#1919 coinmarketcap.com + tradingview.com
  src/config.json
Labels: whitelist request

#1920 c-kamowski.fr + more
  src/config.json
Labels: blacklist request

#1922 get.personaleth.com + more
  src/config.json
Labels: blacklist request

#1923 idexmarketllc.com + more
  src/config.json
Labels: blacklist request

#1925 acuitus.com
  src/config.json
Labels: whitelist request

#1927 ethaction.io + more
  src/config.json
Labels: blacklist request

#1929 eos-platform.net + btcfast.io
  src/config.json
Labels: blacklist request

#1931 add dav.systems
  src/config.json
Labels: blacklist request

#1932 indexmaker-network.com + more
  src/config.json
Labels: blacklist request

#1936 trycrypto.com + atatus.com
  src/config.json
Labels: whitelist request

#1937 eosauthority.info + more
  src/config.json
Labels: blacklist request

#1938 neo-x.info + more
  src/config.json
Labels: blacklist request

#1942 airdropeos.com
  src/config.json
Labels: blacklist request

#1943 get.ethsupport.net + more
  src/config.json
Labels: blacklist request

#1945 myeostrust.com + more
  src/config.json
Labels: blacklist request

#1946 xn--eosauthorty-wcb.com + more
  src/config.json
Labels: blacklist request

#1947 mykrypto.io
  src/config.json
Labels: whitelist request

#1949 ethereum.odyssey.center
  src/config.json
Labels: blacklist request

#1950 remove eosclassic.co
  src/config.json
Labels: whitelist request

#1951 give-ethprize.com + more
  src/config.json
Labels: blacklist request

#1952 ethofficialpage.us + more
  src/config.json
Labels: blacklist request

#1953 ethextra.net
  src/config.json
Labels: blacklist request

#1954 myautocentmarks.com + more
  src/config.json
Labels: blacklist request

#1955 ethereum-event.com + ethereum-giveaway.safe-eth.top
  src/config.json
Labels: blacklist request

#1957 freeethpromo.com
  src/config.json
Labels: blacklist request

#1958 vethorscan.io
  src/config.json
Labels: whitelist request

#1959 eos-authority.com + myethrawallet.com
  src/config.json
Labels: blacklist request

#1962 musk-shares.com + more
  src/config.json
Labels: blacklist request

#1961 Update config.json
  src/config.json
Labels: blacklist request, needs-more-information, whitelist request

#1964 msgcrypto.com
  src/config.json
Labels: whitelist request

#1965 ethereumdrop.info + more
  src/config.json
Labels: blacklist request

#1966 ethgift.net + ethfortune.com
  src/config.json
Labels: blacklist request

#1969 telegram.market
  src/config.json
Labels: blacklist request

#1970 wallet.eostoolkits.io + more
  src/config.json
Labels: blacklist request

#1971 bestrate.org
  src/config.json
Labels: whitelist request

#1974 ethaway.com + more
  src/config.json
Labels: blacklist request

#1975 xn--eosauthorty-jzb.com + more
  src/config.json
Labels: blacklist request

#1978 eosauthorithy.com + ethereumanniversary.org
  src/config.json
Labels: blacklist request

#1979 ethercat.org
  src/config.json
Labels: whitelist request

#1980 validbtc.com + more
  src/config.json
Labels: blacklist request

#1982 dbcrypto.io
  src/config.json
Labels: whitelist request

#1983 myehferwallet.com + more
  src/config.json
Labels: blacklist request

#1973 20180626 user phising report #1654b
  src/config.json
Labels: blacklist request

#1986 myetherwallet-singmgs.top + more
  src/config.json
Labels: blacklist request

#1987 myethswallets.info
  src/config.json
Labels: blacklist request

#1988 myethenrwallet.site + more
  src/config.json
Labels: blacklist request

#1990 teslaforfree.wordpress.com + more
  src/config.json
Labels: blacklist request
