Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-03, with the labels that each got.

#1046 xn--plniex-bxab.com + more exchange idn homograph attack domains
  src/config.json
Labels: blacklist request

#1048 Report tomocoln.io
  src/hosts.txt
Labels: blacklist request

#1047 Report tomocoln.io
  src/config.json
Labels: blacklist request

#1050 usermd.net
  src/config.json
Labels: blacklist request

#1052 dftnity.org
  src/config.json
Labels: blacklist request

#1051 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1053 Update hosts.txt
  src/hosts.txt
Labels: blacklist request

#1054 dfintty.org + more
  src/config.json
Labels: blacklist request

#1055 dfinity.org (fuzzylist)
  src/config.json
Labels: whitelist request

#1057 xfinity.com
  src/config.json
Labels: whitelist request

#1067 affinity.store
  src/config.json
Labels: whitelist request

#1068 mrcrypto.fr
  src/config.json
Labels: whitelist request

#1069 metahusk.com
  src/config.json
Labels: whitelist request

#1071 trinity.tech
  src/config.json
Labels: whitelist request

#1072 callisto-airdrop.com + xn--thabyss-u8a.com
  src/config.json
Labels: blacklist request

#1074 affinity.vc
  src/config.json
Labels: whitelist request

#1082 changlley.org
  src/config.json
Labels: blacklist request

#1079 docai.science
  src/config.json
  src/hosts.txt
Labels: blacklist request

#1083 cobinhood.com & nwcrypto.com
  src/config.json
Labels: whitelist request

#1084 policypal.info + more
  src/config.json
Labels: blacklist request

#1086 remove bitballoon.com
  src/config.json
Labels: whitelist request

#1087 weffkemining.com
  src/config.json
Labels: whitelist request

#1092 Scam site tomocoin.network
  src/config.json
  src/hosts.txt
Labels: blacklist request

#1098 eth.secure-transactionssecure.com + more
  src/config.json
Labels: blacklist request

#1099 eth953883.htmlcomponentservice.com + more
  src/config.json
Labels: blacklist request

#1100 miroskii.com
  src/config.json
Labels: blacklist request

#1104 finity.ai
  src/config.json
Labels: whitelist request

#1102 add twinity.com to whitelist.
  src/config.json
Labels: whitelist request

#1105 gocrypto.me
  src/config.json
Labels: whitelist request

#1106 ezcrypto.guide dbcrypto.com crypto.news
  src/config.json
Labels: whitelist request

#1112 telegram.auction + more
  src/config.json
Labels: blacklist request

#1115 affinity.com + more
  src/config.json
Labels: whitelist request

#1124 binance.bitballoon.com + more
  src/config.json
Labels: blacklist request

#1127 affinity.photography + azcrypto.net
  src/config.json
Labels: whitelist request

#1123 Whitelist affinity.co
  src/config.json
Labels: whitelist request

#1128 ethereum-giveaway.info
  src/config.json
Labels: blacklist request

#1129 bonus.etherpayout.com
  src/config.json
Labels: blacklist request

#1130 gram.vc + more
  src/config.json
Labels: blacklist request

#1132 cosss.io + more
  src/config.json
Labels: blacklist request

#1138 telegra.ph + more
  src/config.json
Labels: blacklist request

#1139 aicrypto.ai + more
  src/config.json
Labels: whitelist request

#1141 blocikchair.info
  src/config.json
Labels: blacklist request

#1131 Adding two new domains to the list
  src/hosts.txt
Labels: blacklist request

#1142 xn--coindes-jhb.com + more
  src/config.json
Labels: blacklist request

#1144 mybinance.info
  src/config.json
Labels: blacklist request

#1148 icoeth.tk
  src/config.json
Labels: blacklist request

#1149 gfinity.net
  src/config.json
Labels: whitelist request

#1150 eth-giveaway.com & syncfab.eu
  src/config.json
Labels: blacklist request

#1153 eth-giveaway.info
  src/config.json
Labels: blacklist request

#1155 myetherwalletico.blogspot.de + more
  src/config.json
Labels: blacklist request

#1156 ico-gram.net
  src/config.json
Labels: blacklist request

#1167 etherscanio.github.io + more
  src/config.json
Labels: blacklist request

#1168 Add celsius-ico[.]network
  src/config.json
Labels: blacklist request

#1170 add celsiuss[.]network
  src/config.json
Labels: blacklist request

#1171 ethereumtrans.com
  src/config.json
Labels: blacklist request

#1172 winity.io + more
  src/config.json
Labels: whitelist request

#1173 originprotocol.online
  src/config.json
Labels: blacklist request

#1174 coinbase-secure-a2k34j.bitballoon.com
  src/config.json
Labels: blacklist request

#1175 funfaircoin.org
  src/config.json
Labels: blacklist request

#1177 tongram.me
  src/config.json
Labels: blacklist request

#1178 ethfreeget.com + etherbonuses.com
  src/config.json
Labels: blacklist request

#1179 icotonsale.com
  src/config.json
Labels: blacklist request

#1180 ethereum-transfer.online
  src/config.json
Labels: blacklist request

#1181 trust-cryptopayment.com
  src/config.json
Labels: blacklist request

#1183 binance-promo.net
  src/config.json
Labels: blacklist request

#1187 eth.hn + more
  src/config.json
Labels: blacklist request

#1188 crypto.ms + vncrypto.info
  src/config.json
Labels: whitelist request

#1189 owainpritchard.co.uk
  src/config.json
Labels: blacklist request

#1193 myetherwalletradeico.blogspot.de
  src/config.json
Labels: blacklist request

#1195 ethgive.github.io + more
  src/config.json
Labels: blacklist request

#1197 etherfreegive.com
  src/config.json
Labels: blacklist request

#1200 work.nelsconsult.com.ng + eth-promo.com
  src/config.json
Labels: blacklist request

#1201 eth-giveaway-vote.bitballoon.com + more
  src/config.json
Labels: blacklist request

#1203 eth.altervista.org
  src/config.json
Labels: blacklist request

#1204 crypto.dance + more
  src/config.json
Labels: whitelist request

#1210 galaxy-es0lutions.com + more
  src/config.json
Labels: blacklist request

#1211 mycrypto.education
  src/config.json
Labels: whitelist request

#1212 etherscan-giveaway.epizy.com
  src/config.json
Labels: blacklist request

#1213 telegram.ceo
  src/config.json
Labels: blacklist request

#1218 coti.cf
  src/config.json
Labels: blacklist request

#1219 geth.cc + more
  src/config.json
Labels: blacklist request

#1222 ethpayment.bitballoon.com + myettherwallet.xyz
  src/config.json
Labels: blacklist request

#1223 coin-zc.com xn--bitcon-mwa.com
  src/config.json
Labels: blacklist request

#1224 metronome-token.io + i-myetherwalnet.com
  src/config.json
Labels: blacklist request

#1226 ethdrop.info
  src/config.json
Labels: blacklist request

#1227 ethpayd.com + more
  src/config.json
Labels: blacklist request

#1228 xn--myetlherallet-341g.com + more
  src/config.json
Labels: blacklist request

#1229 ancrypto.ru
  src/config.json
Labels: whitelist request

#1230 hederashashgraph.com + hederahashgraph.com
  src/config.json
Labels: blacklist request, whitelist request

#1232 telegramsale.com
  src/config.json
Labels: blacklist request

#1233 eths.vu
  src/config.json
Labels: blacklist request

#1238 nnyiictehervvailiatt.com + more
  src/config.json
Labels: blacklist request

#1239 tonpublic.org + ton-telegram.com
  src/config.json
Labels: blacklist request

#1240 myetherwallet.heliohost.org
  src/config.json
Labels: blacklist request

#1242 blnnance.com
  src/config.json
Labels: blacklist request

#1244 coinmakerbot.com + more
  src/config.json
Labels: blacklist request

#1247 dfinery.com + ncrypto.io
  src/config.json
Labels: whitelist request

#1251 auctuss.org
  src/config.json
Labels: blacklist request

#1255 auctus.network & auctus.org
  src/config.json
Labels: blacklist request, whitelist request

#1258 eths.li
  src/config.json
Labels: blacklist request

#1259 tronfoundation.me + more
  src/config.json
Labels: blacklist request

#1263 nnyiicteherwailiatt.com + nnyecthenwellat.com
  src/config.json
Labels: blacklist request

#1264 nuclus.co + actu.fr
  src/config.json
Labels: whitelist request

#1275 update xn--mercadobtcon-mfbd.com
  src/config.json
Labels: blacklist request

#1278 ethgiveaway.club + more
  src/config.json
Labels: blacklist request

#1280 kinecosystem.net + more
  src/config.json
Labels: blacklist request

#1281 afiniti.com + more
  src/config.json
Labels: whitelist request

#1286 myehcrwalilet.com + mynbethernvwallet.com
  src/config.json
Labels: blacklist request
