Repository MetaMask/eth-phishing-detect, pull requests merged in 2018-05, with the labels that each got.

#1523 nem-dns.bitballoon.com
  src/config.json
Labels: whitelist request

#1524 eosreward.io + more
  src/config.json
Labels: blacklist request

#1525 axpire.tech
  src/config.json
Labels: blacklist request

#1528 meythcrrwallet.ru.com + more
  src/config.json
Labels: blacklist request

#1529 blockchaihs.info cken.site
  src/config.json
Labels: blacklist request

#1530 xn--conbase-cfb.com + more
  src/config.json
Labels: blacklist request

#1531 cdnsfiles.com
  src/config.json
Labels: blacklist request

#1533 tronlabsnetwork.com + more
  src/config.json
Labels: blacklist request

#1535 eth-giveaway.updog.co
  src/config.json
Labels: blacklist request

#1536 5000eth.org
  src/config.json
Labels: blacklist request

#1538 giveavvay10000eth.host
  src/config.json
Labels: blacklist request

#1539 eth-giveaway.co.nf
  src/config.json
Labels: blacklist request

#1541 add shivom.sale
  src/config.json
Labels: blacklist request

#1542 verifiedeth.com + more
  src/config.json
Labels: blacklist request

#1543 freeeth.info
  src/config.json
Labels: blacklist request

#1545 myetherwallet.access-checker.com
  src/config.json
Labels: blacklist request

#1546 hederahashgraph.store + more
  src/config.json
Labels: blacklist request

#1548 orchidprotocols.com
  src/config.json
Labels: blacklist request

#1549 xn--mycrpto-k64c.com + more
  src/config.json
Labels: blacklist request

#1550 elon-giveaway.com
  src/config.json
Labels: blacklist request

#1552 Update config.json
  src/config.json
Labels: blacklist request

#1554 Update config.json
  src/config.json
Labels: whitelist request

#1555 Update config.json
  src/config.json
Labels: blacklist request

#1556 Update config.json
  src/config.json
Labels: blacklist request

#1566 Blacklisting a bunch of domains
  src/config.json
Labels: blacklist request

#1568 quarkchain.website
  src/config.json
Labels: blacklist request

#1569 kinecosystem.io
  src/config.json
Labels: blacklist request

#1570 Update config.json
  src/config.json
Labels: blacklist request

#1571 promo-give-ethereum.org + more
  src/config.json
Labels: blacklist request

#1575 ethsafepay.net + more
  src/config.json
Labels: blacklist request

#1579 collect.ethforyou.com + getmyetho.paperplane.io
  src/config.json
Labels: blacklist request

#1582 securetransfer.ethpromotion.com
  src/config.json
Labels: blacklist request

#1583 add dav.icocrowdsale.io
  src/config.json
Labels: blacklist request

#1584 musk-party-gifts.updog.co + more
  src/config.json
Labels: blacklist request

#1585 Update config.json
  src/config.json
Labels: blacklist request

#1586 privcoin.io + more
  src/config.json
Labels: blacklist request

#1587 xn--polonix-17a.com + xn--tro-k5y.com
  src/config.json
Labels: blacklist request

#1589 xn--bifinex-fb4c.com + more
  src/config.json
Labels: blacklist request

#1599 secure-ethereum.tw1.su + more
  src/config.json
Labels: blacklist request

#1596 quarkchain.live
  src/config.json
Labels: blacklist request

#1595 blacklist_domains_1700
  src/config.json
Labels: blacklist request

#1601 etherfree.tech
  src/config.json
Labels: blacklist request

#1602 etherums-givingaway.atspace.tv
  src/config.json
Labels: blacklist request

#1604 ethgiveavvay.site
  src/config.json
Labels: blacklist request

#1607 zclassiccoins.com + more
  src/config.json
Labels: blacklist request

#1606 Whitelist Decrypto.net
  src/config.json
Labels: whitelist request

#1609 5000ethereum.online + more
  src/config.json
Labels: blacklist request

#1610 eth-giveaway.today + more
  src/config.json
Labels: blacklist request

#1613 quarkchains.io + more
  src/config.json
Labels: blacklist request

#1614 pundix.tech
  src/config.json
Labels: blacklist request

#1621 tokenairdrop.typeform.com + more
  src/config.json
Labels: blacklist request

#1623 quarkchain.pl + more
  src/config.json
Labels: blacklist request

#1619 Add audius.co to whitelist
  src/config.json
Labels: whitelist request

#1624 waves-ethereum-eth.org + more
  src/config.json
Labels: blacklist request

#1636 nathanielpopper.promo-eths.com + promo-eths.com
  src/config.json
Labels: blacklist request

#1639 walleteos.org
  src/config.json
Labels: blacklist request

#1640 acus.gov + more
  src/config.json
Labels: whitelist request

#1644 eth-promo.net + more
  src/config.json
Labels: blacklist request

#1646 Update config.json
  src/config.json
Labels: blacklist request

#1647 bittrex-login.com + more
  src/config.json
Labels: blacklist request

#1649 etherdelta.githiub.io + more
  src/config.json
Labels: blacklist request

#1650 ethgift.org + hydroraindrop.typeform.com
  src/config.json
Labels: blacklist request

#1659 remove typeform.com
  src/config.json
Labels: whitelist request

#1661 ethconfirm.info + more
  src/config.json
Labels: blacklist request

#1662 get.ico-eth.org + more
  src/config.json
Labels: blacklist request

#1663 klareol5.ru + more
  src/config.json
Labels: blacklist request

#1664 mew-ehterwallat.com + more
  src/config.json
Labels: blacklist request

#1666 eth4everyone.com + ethtransaction.ezyro.com
  src/config.json
Labels: blacklist request

#1668 tron-block.com + more
  src/config.json
Labels: blacklist request

#1667 ethgive.net
  src/config.json
Labels: blacklist request

#1669 xn--mytherwallet-fvb.net + more
  src/config.json
Labels: blacklist request

#1670 givefree-eth.com + more
  src/config.json
Labels: blacklist request

#1671 brm.10000eth-gift.com + more
  src/config.json
Labels: blacklist request

#1673 wallets-ether.com
  src/config.json
Labels: blacklist request

#1675 secure375446884521.safeethpay.com + more
  src/config.json
Labels: blacklist request

#1676 my-etherwallsecure.com
  src/config.json
Labels: blacklist request

#1677 claim-eth.com + more
  src/config.json
Labels: blacklist request

#1678 quarkchain.pub
  src/config.json
Labels: blacklist request

#1681 myerherwallet.tk + more
  src/config.json
Labels: blacklist request

#1682 ethpromo.org + more
  src/config.json
Labels: blacklist request

#1686 lendium.tech + more
  src/config.json
Labels: blacklist request

#1687 mycrypto.promo + more
  src/config.json
Labels: blacklist request

#1691 tomochain.tech
  src/config.json
Labels: blacklist request

#1697 geteth.online + more
  src/config.json
Labels: blacklist request

#1700 air-eos.com
  src/config.json
Labels: blacklist request

#1701 Update config.json
  src/config.json
Labels: blacklist request

#1702 coinbase.pro-fork.com
  src/config.json
Labels: blacklist request

#1703 eoslaunch.io
  src/config.json
Labels: blacklist request

#1704 10000eth.net
  src/config.json
Labels: blacklist request

#1705 ethg.me + more
  src/config.json
Labels: blacklist request

#1706 ether-giveaway.net + more
  src/config.json
Labels: blacklist request

#1707 coinbaseverifier.com
  src/config.json
Labels: blacklist request

#1715 ethnow.me + more
  src/config.json
Labels: blacklist request

#1716 xn--myethrwalt-zmbt05c.com + more
  src/config.json
Labels: blacklist request

#1722 crypto.tube + more
  src/config.json
Labels: blacklist request, whitelist request

#1723 actas.club
  src/config.json
Labels: whitelist request

#1724 xn--mytherwalt-smbh17c.com
  src/config.json
Labels: blacklist request

#1727 ethtopromo.org + more
  src/config.json
Labels: blacklist request

#1728 etherbonus.net
  src/config.json
Labels: blacklist request

#1730 cultus.com
  src/config.json
Labels: whitelist request

#1731 idex-info.com + more
  src/config.json
Labels: blacklist request
