Repository MetaMask/eth-phishing-detect, pull requests merged in 2019-10, with the labels that each got.

#3375 rippleinsights.live + more
  src/config.json
Labels: blacklist request

#3376 whitelist etherscan.com
  src/config.json
Labels: whitelist request

#3387 ildex.host + more
  src/config.json
Labels: blacklist request

#3395 investmentworld.site + more
  src/config.json
Labels: blacklist request

#3396 ethaget.com + more
  src/config.json
Labels: blacklist request

#3397 xrpinsights.live
  src/config.json
Labels: blacklist request

#3403 claimbtc.org + more
  src/config.json
Labels: blacklist request

#3411 earnxrp.live + more
  src/config.json
Labels: blacklist request

#3413 chianlink.io + more
  src/config.json
Labels: blacklist request

#3418 mc2020get.com + more
  src/config.json
Labels: blacklist request

#3419 added blacklist site
  src/config.json
Labels: blacklist request, whitelist request

#3422 dex-start.net + more
  src/config.json
Labels: blacklist request

#3423 myetherwallet-extra-bonuses.000webhostapp.com
  src/config.json
Labels: blacklist request

#3424 edfinity.com + more
  src/config.json
Labels: whitelist request
