Repository MetaMask/eth-phishing-detect, pull requests merged in 2020-11, with the labels that each got.

#4324 uniswapofficial.com + more
  src/config.json
Labels: blacklist request

#4325 uniswapairdrop.info
  src/config.json
Labels: blacklist request

#4333 ocean-airdrop.com + more
  src/config.json
Labels: blacklist request

#4334 airdropocean.com
  src/config.json
Labels: blacklist request

#4335 whitelist edge.network + more
  src/config.json
Labels: whitelist request

#4345 ledgerql.com
  src/config.json
Labels: whitelist request

#4347 xn--rpple-n4a.net + metamask.org-swap.app
  src/config.json
Labels: blacklist request

#4362 enledger.io + enledger.com
  src/config.json
Labels: whitelist request

#4365 whitelist and fuzzy launchpad.ethereum.org
  src/config.json
Labels: whitelist request

#4367 musk-coins.com + more
  src/config.json
Labels: blacklist request

#4369 eth67.blogspot.com + airdrop-ocean.com
  src/config.json
Labels: blacklist request

#4374 blocked due to mycrypto fuzzylist
  src/config.json
Labels: whitelist request

#4375 stellar-info.org + more
  src/config.json
Labels: blacklist request

#4376 oceanairdrop.info + more
  src/config.json
Labels: blacklist request

#4377 Batch add registered and possible ledger.com homographs
  src/config.json
Labels: blacklist request

#4331 Added hedget.com to whitelist
  src/config.json
Labels: whitelist request

#4378 airdrop-uniswap.com
  src/config.json
Labels: blacklist request

#4386 Add ladder.to to whitelist
  src/config.json
Labels: whitelist request

#4395 money-tesla.com
  src/config.json
Labels: blacklist request

#4391 Update config.json
  src/config.json
Labels: blacklist request

#4398 dropmusk.in
  src/config.json
Labels: blacklist request

#4399 uniswap.bid + more
  src/config.json
Labels: blacklist request

#4400 claimuni.com + more
  src/config.json
Labels: blacklist request

#4404 polkadot-airdrop.info + more
  src/config.json
Labels: blacklist request

#4419 yearnyfi.blogspot.com + more
  src/config.json
Labels: blacklist request

#4425 plckle.finance + more
  src/config.json
Labels: blacklist request

#4427 crypto-gives.s3.us-east-2.amazonaws.com + more
  src/config.json
Labels: blacklist request

#4432 stellar.org.ma + more
  src/config.json
Labels: blacklist request

#4434 xeth2.github.io
  src/config.json
Labels: blacklist request

#4436 tesla-btc.info + more
  src/config.json
Labels: blacklist request

#4437 geminigift.org + more
  src/config.json
Labels: blacklist request

#4442 yfiairdrop.com + more
  src/config.json
Labels: blacklist request

#4446 makerdao-info.com + more
  src/config.json
Labels: blacklist request

#4403 new curve phishing site
  src/config.json
  src/hosts.txt
Labels: blacklist request

#4451 takebtc.net + more
  src/config.json
Labels: blacklist request

#4455 chainlink.click + more
  src/config.json
Labels: denylist request

#4463 ripplebonus.us + more
  src/config.json
Labels: denylist request

#4467 installmeta.com + more
  src/config.json
Labels: denylist request

#4462 Add fake aave site to blacklist
  src/config.json
Labels: denylist request

#4468 88mph.app.defi-universe.vip + more
  src/config.json
Labels: denylist request

#4469 Add ledger.com-device.id46267.app
  src/config.json
Labels: denylist request

#4470 charles-hoskinson.live + more
  src/config.json
Labels: denylist request
