Repository MetaMask/eth-phishing-detect, pull requests merged in 2021-09, with the labels that each got.

#5366 Prevent fuzzy match on reviews site
  src/config.json
Labels: allowlist request

#5369 metasmasks.io
  src/config.json
Labels: denylist request

#5368 Add "victus.finance" to the whitelist.
  src/config.json
Labels: allowlist request

#5442 akswap.net
  src/config.json
Labels: denylist request

#5452 ff9.info
  src/config.json
Labels: denylist request

#5464 zepe.vip
  src/config.json
Labels: denylist request

#5461 Phishing sites received through email asking for seeds
  src/config.json
Labels: denylist request

#5465 abchange.org
  src/config.json
Labels: denylist request

#5466 Updated DxSale Fake Links
  src/config.json
Labels: denylist request

#5476 Adding Opensea phishing site reported via ZD
  src/config.json
Labels: denylist request

#5478 adding phishing site reported in ZD
  src/config.json
Labels: denylist request

#5534 Facebook ad with phishing site
  src/config.json
Labels: denylist request

#5499 New Phishing Pages DxSale
  src/config.json
Labels: denylist request

#5525 cpensell.co + more
  src/config.json
Labels: denylist request, needs-more-information
