Repository MetaMask/eth-phishing-detect, pull requests merged in 2021-02, with the labels that each got.

#4649 metamask.io-install.com + more
  src/config.json
Labels: denylist request

#4650 receiveuniswap.com + more
  src/config.json
Labels: denylist request

#4651 univwaps.com + more
  src/config.json
Labels: denylist request

#4652 walletsconnect.online
  src/config.json
Labels: denylist request

#4654 walletsconnect.top
  src/config.json
Labels: denylist request

#4658 walletsconnect.org
  src/config.json
Labels: denylist request

#4659 synthetix.us
  src/config.json
Labels: denylist request

#4661 coinbase.com.auth-value-token-9929929.ru + more
  src/config.json
Labels: denylist request

#4662 uniswapgiveaway.com + sushiairdrop.net
  src/config.json
Labels: denylist request

#4664 giveawayuniswap.com + more
  src/config.json
Labels: denylist request

#4668 uniswapback.com + more
  src/config.json
Labels: denylist request

#4165 please blacklist yearnson.finance
  src/config.json
  src/hosts.txt
Labels: denylist request

#4608 adalife.io - phishing
  src/config.json
Labels: denylist request, needs-more-information

#1308 metabase.cc
  src/config.json
Labels: allowlist request

#4681 coinwoz.com + more
  src/config.json
Labels: denylist request

#4683 myetpwallet.000webhostapp.com + more
  src/config.json
Labels: denylist request

#4694 accounts-binance-log-in.com + more
  src/config.json
Labels: denylist request

#4695 dpitokendrops.com + more
  src/config.json
Labels: denylist request

#4696 harvestfinance.co + more
  src/config.json
Labels: denylist request

#4697 thebitcoineraapp.com + more
  src/config.json
Labels: denylist request

#4703 oneish.xyz + more
  src/config.json
Labels: denylist request

#4704 musk.help + more
  src/config.json
Labels: denylist request

#4707 elontrust.com + more
  src/config.json
Labels: denylist request

#4714 takeyourcrypto.info + more
  src/config.json
Labels: denylist request

#4719 elonmusk.help + more
  src/config.json
Labels: denylist request

#4720 lotto.fashion
  src/config.json
Labels: denylist request

#4722 bnbget.org + more
  src/config.json
Labels: denylist request

#4726 remove genoverde.com
  src/config.json
Labels: allowlist request

#4727 makerdao.network
  src/config.json
Labels: allowlist request

#4730 Adding a Stellar phishing website: stellar.org.ht
  example/bundle.js
  src/config.json
Labels: denylist request

#4732 elontesla.me + more
  src/config.json
Labels: denylist request

#4736 dodoex.us + more
  src/config.json
Labels: denylist request

#4738 restorewalletsio.link + more
  src/config.json
Labels: denylist request
