Repository MetaMask/eth-phishing-detect, pull requests merged in 2021-08, with the labels that each got.

#5239 app.sushicom.site
  src/config.json
Labels: denylist request

#5247 sushi-swap.net
  src/config.json
Labels: denylist request

#5260 vesperbit.com + more
  src/config.json
Labels: denylist request

#5265 add recent reports
  src/config.json
Labels: denylist request

#5275 badgerdao.app + badgerdao.io
  src/config.json
Labels: denylist request

#5304 Update config.json
  src/config.json
Labels: allowlist request

#5299 phishing site used in fake metamask emails
  src/config.json
Labels: denylist request

#5348 allowlist finty.com
  src/config.json
Labels: allowlist request

#5269 Reported through Telegram
  src/config.json
Labels: needs-more-information
