Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-06, with the labels that each got.

#7567 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7574 allow opensay.co & opensay.xyz
  src/config.json
Labels: allowlist request

#7581 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7578 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7597 Add Hop phishing url to blacklist
  src/config.json
Labels: denylist request

#7585 add goblinwilldoit.wtf, goblintown.world, boki-nft.live
  src/config.json
Labels: denylist request

#7607 Add helpcenter-opensea.io to blacklist
  src/config.json
Labels: denylist request

#7624 Adding Phishing Sites to Blacklist [20]
  src/config.json
Labels: denylist request

#7635 Trezor 20220608 Phishing
  src/config.json
Labels: denylist request

#7656 pieceofshit.wtf is not a scam
  src/config.json
Labels: allowlist request

#7589 ocmkarma-mint.netlify.app + more
  src/config.json
Labels: denylist request

#7663 Allowlist infinity.careers (#7613)
  src/config.json
Labels: allowlist request

#7687 Trezor 20220614 Phishing
  src/config.json
Labels: denylist request

#7707 Adding Phishing Sites to Blacklist [6]
  src/config.json
Labels: denylist request

#7700 goblin-town.net + more
  src/config.json
Labels: denylist request

#7726 etherscan-approve.negle-universet.dk
  src/config.json
Labels: denylist request

#7760 Adding Phishing Sites to Blacklist [24]
  src/config.json
Labels: denylist request

#7792 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7674 Fix arctis.tech
  src/config.json
Labels: allowlist request

#7691 Updated blacklist
  src/config.json
Labels: denylist request

#7633 Add sudoswap.xyz to fuzzylist
  src/config.json
Labels: allowlist request, needs-more-information

#7836 Adding Phishing Sites to Blacklist [47]
  src/config.json
Labels: denylist request

#7849 metamaskbridge.org
  src/config.json
Labels: denylist request
