Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-09, with the labels that each got.

#8340 Add pudgypenguins.gift to the blacklist
  src/config.json
Labels: denylist request

#8325 Update config.json
  src/config.json
Labels: denylist request

#8328 High Priority Dao Impersonation
  src/config.json
Labels: denylist request

#8330 Add openseal.xyz to the blacklist
  src/config.json
Labels: denylist request

#8336 Add ticket-opensea.com to the blacklist
  src/config.json
Labels: denylist request

#8337 Seed Phrase Phishing Site
  src/config.json
Labels: denylist request

#8344 Seed Phrase Theft
  src/config.json
Labels: denylist request

#8343 remove cross.swapz.app
  src/config.json
Labels: allowlist request

#8346 Update config.json
  src/config.json
Labels: denylist request

#8351 Update config.json
  src/config.json
Labels: denylist request

#8353 Update config.json
  src/config.json
Labels: denylist request

#8362 Site Impersonating Polygon
  src/config.json
Labels: denylist request

#8367 Seed Phrase Theft
  src/config.json
Labels: denylist request

#8293 Trezor 20220825 Phishing
  src/config.json
Labels: denylist request

#8390 Update config.json
  src/config.json
Labels: denylist request

#8395 whitelist openmeta.xyz, a legitimate project caught by fuzzylist
  src/config.json
Labels: allowlist request

#8405 Update config.json
  src/config.json
Labels: denylist request

#8423 Seed phrase theft
  src/config.json
Labels: denylist request

#8416 Update config.json
  src/config.json
Labels: denylist request

#8414 Adding Phishing Sites to Blacklist [9]
  src/config.json
Labels: denylist request

#8433 Update config.json
  src/config.json
Labels: denylist request

#8437 PR for infinity.app domain again with more infomation.
  src/config.json
Labels: needs-more-information

#8476 Update config.json
  src/config.json
Labels: denylist request

#8497 Update config.json
  src/config.json
Labels: denylist request

#8516 Update config.json
  src/config.json
Labels: denylist request

#8502 Added Drivity.org on the whitelist
  src/config.json
Labels: needs-more-information

#8518 Add fake Across domain
  src/config.json
Labels: denylist request

#8554 Update config.json
  src/config.json
Labels: denylist request

#8550 adding phishing sites to blacklist [22]
  src/config.json
Labels: denylist request

#8580 Trezor 20220928 Phishing
  src/config.json
Labels: denylist request

#8604 whitelist fair.xyz
  src/config.json
Labels: allowlist request

#8623 Enhancement/top dapps
  test/dapps.json
Labels: enhancement

#8622 adding keeper wallet url's to whitelist
  src/config.json
Labels: allowlist request

#8581 CLI to add blacklisted sites
  README.md
  package.json
  src/blacklist.js
Labels: enhancement

#8616 adding phishing site
  src/config.json
Labels: denylist request

#8630 Update config.json
  src/config.json
Labels: denylist request
