Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-12, with the labels that each got.

#9765 Remove Site from Blocklist [1] & Add Site to Allowlist [1]
  src/config.json
Labels: allowlist request

#9732 Adding scamming website to blacklist
  src/config.json
Labels: denylist request

#9783 Add Phishing Sites to Blocklist [54]
  src/config.json
Labels: denylist request

#9780 adding phishing site to blacklist [1]
  src/config.json
Labels: denylist request

#9781 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9784 Add new phishing domains
  src/config.json
Labels: denylist request

#9791 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9797 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9800 Add new phishing domains
  src/config.json
Labels: denylist request

#9805 blocklist add google ad scams impersonating cow.fi
  src/config.json
Labels: denylist request

#9810 Add ticket-seaport.io to the blocklist
  src/config.json
Labels: denylist request

#9828 mmskairdrop.com
  src/config.json
Labels: denylist request

#9839 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#9844 Add Phishing Sites to Blocklist [4]
  src/config.json
Labels: denylist request

#9845 Add Legitimate Sites to Allowlist [1]
  src/config.json
Labels: allowlist request

#9854 block 25 scam URLs
  src/config.json
Labels: denylist request

#9855 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9880 adding site to allowlist [1]
  src/config.json
Labels: allowlist request

#9864 Add Phishing Sites to Blocklist [21]
  src/config.json
Labels: denylist request

#9872 Block 7 bakeryswap scams
  src/config.json
Labels: denylist request

#9882 Block another fraudulent Across domain
  src/config.json
Labels: denylist request

#9887 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#9890 Add new phishing domains
  src/config.json
Labels: denylist request

#9891 Update config.json
  src/config.json
Labels: denylist request

#9896 Add Phishing Sites to Blocklist [22]
  src/config.json
Labels: denylist request

#9909 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9893 Block 41 scam URLs
  src/config.json
Labels: denylist request

#9924 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#9923 Add new phishing domains
  src/config.json
Labels: denylist request

#9921 Add coinmarlketcap and cckpunch into blacklist
  src/config.json
Labels: denylist request

#9925 Add Legitimate Sites to Allowlist [3]
  src/config.json
Labels: allowlist request

#9931 Add Legitimate Sites to Allowlist [10]
  src/config.json
Labels: allowlist request

#9910 Update config.json
  src/config.json
Labels: denylist request

#9903 Added fake captcha, fake metamask scam
  src/config.json
Labels: denylist request

#9937 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#9933 add scam urls targeting pudgy penguins
  src/config.json
Labels: denylist request

#9934 add scam targeting blur
  src/config.json
Labels: denylist request

#9935 Add Phishing Sites to Blocklist [10]
  src/config.json
Labels: denylist request

#9950 adding phishing sites to blocklist [2] adding one site to allowlist
  src/config.json
Labels: denylist request, allowlist request

#9932 Add new phishing domains
  src/config.json
Labels: denylist request

#9972 Add Phishing Sites to Blocklist [17]
  src/config.json
Labels: denylist request

#9976 remove gangirls from harmful sites
  src/config.json
Labels: allowlist request

#9952 adding phishing sites to blocklist [2]
  src/config.json
Labels: denylist request

#9986 remove pirategirls.xyz from blocklist #9917
  src/config.json
Labels: allowlist request

#10002 adding phishing sites to blocklist [2] adding one site to allowlist
  src/config.json
Labels: denylist request, allowlist request

#10008 Block 43 scam URLs
  src/config.json
Labels: denylist request

#10010 adding phishing sites to blacklist [2]
  src/config.json
Labels: denylist request

#10014 adding phishing sites to blocklist [3]
  src/config.json
Labels: denylist request

#10025 adding phishing site to blocklist [1]
  src/config.json
Labels: denylist request

#10028 add to blocklist scams targeting Pudgy Penguins
  src/config.json
Labels: denylist request

#10045 Phishing Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#10048 Add new phishing domains
  src/config.json
Labels: denylist request

#10061 add to blocklist scams targeting Pudgy Penguins
  src/config.json
Labels: denylist request

#10057 Add Phishing Sites to Blocklist [24]
  src/config.json
Labels: denylist request

#10039 add to blocklist scams targeting Pudgy Penguins
  src/config.json
Labels: denylist request

#10070 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#10072 Scams 20221227
  src/config.json
Labels: denylist request

#10056 Update config.json
  src/config.json
Labels: denylist request

#9971 PhishingDetector: return matching entry for allowlist,blocklist check
  src/detector.js
Labels: improvement

#10102 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#10105 Phishing website which took over the MutantHounds twitter account
  src/config.json
Labels: denylist request
