Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-03, with the labels that each got.

#6746 mysecure-dnsserver.com + more
  src/config.json
Labels: denylist request

#6726 Whitelist: openrep.foundation
  src/config.json
Labels: allowlist request

#6732 Allowlist sites 2022-02-01 to 2022-02-07
  src/config.json
Labels: allowlist request

#6762 company-atomic.com
  src/config.json
Labels: denylist request

#6826 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6836 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6878 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6891 Bugfix/afqdn check
  package.json
  src/detector.js
  test/index.js
Labels: enhancement

#6885 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6905 live-nft-mint.com + ape-coin.net
  src/config.json
Labels: denylist request

#6868 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6871 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6904 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6706 whitelist.md
  doc/fuzzylist.md
  doc/whitelist.md
Labels: improvement

#6914 ape-coin.art + more
  src/config.json
Labels: denylist request

#6908 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6916 adding phishing sites from Phishing email
  src/config.json
Labels: denylist request

#6918 Added sites to blacklist.
  src/config.json
Labels: denylist request

#6924 apecoin.events
  src/config.json
Labels: denylist request

#6919 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6921 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#6996 removing erroneously blocked adrunner site
  src/config.json
Labels: allowlist request

#6999 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7007 cross-chainbot.org
  src/config.json
Labels: denylist request

#7008 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7009 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7001 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7011 Remove app.cryptoblades.io from Blacklist
  src/config.json
Labels: allowlist request
