Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-11, with the labels that each got.

#9243 Add Phishing Sites to Blacklist [16]
  src/config.json
Labels: denylist request

#9265 add zksync.crew3.xyz to whitelist
  src/config.json
Labels: allowlist request

#9268 raydium.fi
  src/config.json
Labels: denylist request

#9260 Site Impersonating Polygon
  src/config.json
Labels: allowlist request

#9253 Add 45 various scams
  src/config.json
Labels: denylist request

#9280 Block balancer.rest - fake balancer.fi imitation
  src/config.json
Labels: denylist request

#9248 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9286 Block 19 scams
  src/config.json
Labels: denylist request

#9323 Site Impersonating Polygon with Malicious Intent
  src/config.json
Labels: denylist request

#9308 Block 57 scams
  src/config.json
Labels: denylist request

#9309 Add airdrops-opensea.io to the blacklist
  src/config.json
Labels: denylist request

#9294 Block fake uniswap airdrop spammed on Twitter
  src/config.json
Labels: denylist request

#9307 Add Legitimate Sites to Whitelist [3]
  src/config.json
Labels: allowlist request

#9313 Add phishing domains to blocklist
  src/config.json
Labels: denylist request

#9327 batch update
  src/config.json
Labels: allowlist request

#9353 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9346 Add various phishing, malware domains
  src/config.json
Labels: denylist request

#9343 adding sites to allowlist [5]
  src/config.json
Labels: allowlist request

#9338 Add legitimate web site of Finiti company to whitelist
  src/config.json
Labels: allowlist request

#9358 Add Phishing Sites to Blocklist [17]
  src/config.json
Labels: denylist request

#9385 Block 25 scams
  src/config.json
Labels: denylist request

#9390 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#9391 Site Impersonating Polygon
  src/config.json
Labels: denylist request

#9395 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#9397 Sites impersonating Polygon
  src/config.json
Labels: denylist request

#9394 Add various phishing domains
  src/config.json
Labels: denylist request

#9399 phishing site added
  src/config.json
Labels: denylist request

#9382 Add Phishing Sites to Blocklist [16]
  src/config.json
Labels: denylist request

#9376 adding sites to allowlist [2], removing blocklist [-1]
  src/config.json
Labels: allowlist request

#9409 Trezor 20221114 Phishing
  src/config.json
Labels: denylist request

#9403 Add new phishing domains
  src/config.json
Labels: denylist request

#9416 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9408 Block 89 scams
  src/config.json
Labels: denylist request

#9424 Trezor 20221115 Phishing
  src/config.json
Labels: denylist request

#9426 Sites impersonating Polygon
  src/config.json
Labels: denylist request

#9429 Add seairdrop.com to the blacklist
  src/config.json
Labels: denylist request

#9433 Add Phishing Sites to Blocklist [11]
  src/config.json
Labels: denylist request

#9437 3commas allowlist
  src/config.json
Labels: denylist request, allowlist request

#9440 block 182 scams
  src/config.json
Labels: denylist request

#9443 block 38 scams
  src/config.json
Labels: denylist request

#9441 Add opensea-claim.com/ to the blacklist
  src/config.json
Labels: denylist request

#9439 kufrex.com coinwan.io
  src/config.json
Labels: denylist request

#9450 block 100 scams
  src/config.json
Labels: denylist request

#9448 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9461 Add Legitimate Sites to Allowlist [1]
  src/config.json
Labels: allowlist request

#9462 Block 75 scams
  src/config.json
Labels: denylist request

#9459 Add phishing url to blacklist
  src/config.json
Labels: denylist request

#9460 Add Phishing Sites to Blocklist [6]
  src/config.json
Labels: denylist request

#9463 Update config.json
  src/config.json
Labels: denylist request

#9465 Site impersonating polygon
  src/config.json
Labels: denylist request

#9471 Trezor 20221121 Phishing
  src/config.json
Labels: denylist request

#9412 Introduce Trezor and SatoshiLabs domains to fuzzylist
  src/config.json
Labels: improvement

#9472 Trezor 20221122 Phishing
  src/config.json
Labels: denylist request

#9486 tenor.com and tenzor.capital
  src/config.json
Labels: allowlist request

#9519 Update config.json
  src/config.json
Labels: denylist request

#9558 update whitelist with Tezos websites
  src/config.json
Labels: allowlist request

#9595 Add Legitimate Sites to Allowlist [1]
  src/config.json
Labels: allowlist request

#9597 tezos.domains
  src/config.json
Labels: allowlist request

#9572 Update whitelist with trever.io domain
  src/config.json
Labels: allowlist request

#9590 Add Razor.network and Razorscan.io in allowlist
  src/config.json
Labels: allowlist request

#9605 2 phishing opensea links
  src/config.json
Labels: denylist request

#9609 Block 448 advance fee fraud URLs (419) - [Retrospective]⚰
  src/config.json
Labels: denylist request

#9626 coinsolutions.web.app + more
  src/config.json
Labels: denylist request

#9630 Add Phishing Sites to Blocklist [16]
  src/config.json
Labels: denylist request

#9645 Trezor 20221125 Phishing
  src/config.json
Labels: denylist request

#9644 block 25 scams
  src/config.json
Labels: denylist request

#9648 Trezor 20221126 Phishing
  src/config.json
Labels: denylist request

#9650 block 59 scam URLs
  src/config.json
Labels: denylist request

#9691 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9697 Add known CoinTracker phishing domains
  src/config.json
Labels: denylist request

#9703 block scam uniswap airdrop - eligible-uni.org
  src/config.json
Labels: denylist request

#9705 block 23 scams of the same flavor - fake metamask merge
  src/config.json
Labels: denylist request

#9708 Add new phishing domain
  src/config.json
Labels: denylist request

#9716 Trezor 20221129 Phishing
  src/config.json
Labels: denylist request

#9717 add scam sites to blocklist impersonating cow swap real site cow.fi
  src/config.json
Labels: denylist request

#9722 add ens.codes twitter scam to blocklist
  src/config.json
Labels: denylist request

#9724 block 77 fraudulent URLs
  src/config.json
Labels: denylist request

#9734 Site impersonating Polygon
  src/config.json
Labels: denylist request

#9739 adidasnfts.net + more
  src/config.json
Labels: denylist request

#9741 add läyerzero.network & layerzerȯ.network to blacklist
  src/config.json
Labels: denylist request

#9738 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#9742 tezos.finance
  src/config.json
Labels: allowlist request
