Repository MetaMask/eth-phishing-detect, pull requests merged in 2022-04, with the labels that each got.

#7066 azuki-drop.com + more
  src/config.json
Labels: denylist request

#7075 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7081 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7092 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7093 Adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7095 adding phishing sites
  src/config.json
Labels: denylist request

#7106 Remove from blocklist & allowlist officialnft.xyz
  src/config.json
Labels: allowlist request, needs-more-information

#7131 serversync.netlify.app
  src/config.json
Labels: denylist request

#7132 connectingauth.me + more
  src/config.json
Labels: denylist request

#7135 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7097 Allowlist sites 2022-04-01 to 2022-04-07
  src/config.json
Labels: allowlist request

#7113 Allowlist sites 2022-04-08 to 2022-04-14
  src/config.json
Labels: allowlist request

#7114 Allowlist sites 2022-03-08 to 2022-03-14
  src/config.json
Labels: allowlist request

#7150 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7160 nft-moonbirds.net
  src/config.json
Labels: denylist request

#7165 azukishop.live + more
  src/config.json
Labels: denylist request

#7170 adding phishing sites
  src/config.json
Labels: denylist request

#7169 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7178 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7179 moonbird.claims + waliet-polgyon.network
  src/config.json
Labels: denylist request

#7195 add optimism-sale.com
  src/config.json
Labels: denylist request

#7191 add supports-opensea.com to blacklist
  src/config.json
Labels: denylist request

#7213 Allow roobet.com - a few issues opened
  src/config.json
Labels: allowlist request

#7209 add optimism-token.io
  src/config.json
Labels: denylist request

#7217 adding 41 domains to blocklist
  src/config.json
Labels: denylist request

#7200 mintmoonbirds.com + more
  src/config.json
Labels: denylist request

#7224 opensea-appeal.com
  src/config.json
Labels: denylist request

#7225 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7226 moonbirds.id + more
  src/config.json
Labels: denylist request

#7221 allow euler.finance, block phishing sites
  src/config.json
Labels: denylist request, allowlist request

#7228 moonbirdsxyz.co + more
  src/config.json
Labels: denylist request

#7229 mcdex-defi.com + more
  src/config.json
Labels: denylist request

#7231 boredapeyc.design + more
  src/config.json
Labels: denylist request

#7240 moonbirds-airdrop.com + more
  src/config.json
Labels: denylist request

#7244 adding phishing sites to blacklist
  src/config.json
Labels: denylist request

#7252 adding phishing websites to blacklist
  src/config.json
Labels: denylist request

#7250 Add a batch of phishing sites related to polkastarter
  src/config.json
Labels: denylist request

#7259 metamask-re.jatra-apps.org + more
  src/config.json
Labels: denylist request

#7262 mint-optimism.top + more
  src/config.json
Labels: denylist request
