Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-01, with the labels that each got.

#10121 Add Phishing Sites to Blocklist [40]
  src/config.json
Labels: denylist request

#10159 adding phishing site to blocklist [1]
  src/config.json
Labels: denylist request

#10162 Adding phishing sites to blocklist [2]
  src/config.json
Labels: denylist request

#10170 Block 21 scam URLs
  src/config.json
Labels: denylist request

#10134 resolve ethberlin and goerli testnet
  src/config.json
Labels: allowlist request

#10169 Add new phishing domains
  src/config.json
Labels: denylist request

#10177 Add Phishing Sites to Blocklist [18]
  src/config.json
Labels: denylist request

#10200 Site Impersonating Polygon
  src/config.json
Labels: denylist request

#10190 add to blocklist scams targetting Pudgy Penguins
  src/config.json
Labels: denylist request

#10188 Block fraudulent domain
  src/config.json
Labels: denylist request

#10174 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#10241 remove herokuapp.com from the blacklist
  src/config.json
Labels: allowlist request

#10179 Add Legitimate Sites to Allowlist [2]
  src/config.json
Labels: allowlist request

#10157 adding phishing site to blocklist [1]
  src/config.json
Labels: denylist request, allowlist request

#10164 Add phishing sites to blocklist
  src/config.json
Labels: denylist request

#10291 Add new phishing domains
  src/config.json
Labels: denylist request

#10299 add to blocklist scams targeting Pudgy Penguins
  src/config.json
Labels: denylist request

#10334 Add fake chimpers link to blacklist
  src/config.json
Labels: denylist request

#10369 Sites impersonating Polygon
  src/config.json
Labels: denylist request

#10372 Add scams targetting Pudgy Penguins
  src/config.json
Labels: denylist request

#10365 Scams 20230111
  src/config.json
Labels: denylist request

#10374 Add phishing sites to blocklist
  src/config.json
Labels: denylist request

#10373 Add new phishing domains
  src/config.json
Labels: denylist request

#10391 Block 43 scam URLs
  src/config.json
Labels: denylist request

#10386 Add phishing sites to blocklist
  src/config.json
Labels: denylist request

#10390 Add new phishing domains
  src/config.json
Labels: denylist request

#10426 Add Phishing Sites to Blocklist [30]
  src/config.json
Labels: denylist request

#10483 Add Phishing Sites to Blocklist [25]
  src/config.json
Labels: denylist request

#10498 Remove Legitimate Sites from Blocklist [4]
  src/config.json
Labels: allowlist request

#10499 Add a batch of phishing sites related to polkastarter
  src/config.json
Labels: denylist request

#10494 Add Phishing Sites to Blocklist [15]
  src/config.json
Labels: denylist request

#10510 Add scams targetting Pudgy Penguins
  src/config.json
Labels: denylist request

#10509 removing site from blocklist [1]
  src/config.json
Labels: allowlist request

#10511 adding phishing sites to blocklist
  src/config.json
Labels: denylist request

#10520 Add scams targetting Bored Apes
  src/config.json
Labels: denylist request

#10518 Add scams targetting Bored Apes
  src/config.json
Labels: denylist request

#10514 Add scams targetting Optimism
  src/config.json
Labels: denylist request

#10512 Add phishing sites to blocklist
  src/config.json
Labels: denylist request

#10522 Add scams targetting Pudgy Penguins
  src/config.json
Labels: denylist request

#10431 Scams 202301113
  src/config.json
Labels: denylist request

#10557 Add Legitimate Sites to Allowlist [40]
  src/config.json
Labels: allowlist request

#10655 Add Phishing Sites to Blocklist [23]
  src/config.json
Labels: denylist request

#10547 Add Phishing Sites to Blocklist [31]
  src/config.json
Labels: denylist request

#10554 Remove Site from Blocklist [1]
  src/config.json
Labels: allowlist request

#10840 adding phishing sites to blocklist [8]
  src/config.json
Labels: denylist request

#11193 Add Phishing Sites to Blocklist [10]
  src/config.json
Labels: denylist request

#11244 Add new phishing domains
  src/config.json
Labels: denylist request

#11248 Add scams targetting Azuki
  src/config.json
Labels: denylist request

#11240 Add Sites to Blocklist [18]
  src/config.json
Labels: denylist request

#11318 Add scams targeting Metawin and Bored Apes Sewer Pass
  src/config.json
Labels: denylist request

#11299 Add mee6.tf
  src/config.json
Labels: denylist request

#11284 Add new phishing domains
  src/config.json
Labels: denylist request

#11307 Add scams targetting Bored Apes Sewer Pass
  src/config.json
Labels: denylist request

#11315 Add new phishing domains
  src/config.json
Labels: denylist request

#11323 Scams 20230130
  src/config.json
Labels: denylist request

#11328 Block 102 scam URLs
  src/config.json
Labels: denylist request

#11347 Add Phishing Sites to Blocklist [30]
  src/config.json
Labels: denylist request
