Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-07, with the labels that each got.

#12960 Block 27 scams
  src/config.json
Labels: blocklist request

#12983 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#12985 Block 204 scams promoted via twitter "VeRiFiEd" 🤡 profiles
  src/config.json
Labels: blocklist request

#13004 Add sites to blocklist [17]
  src/config.json
Labels: blocklist request

#13023 Add sites to blocklist [17]
  src/config.json
Labels: blocklist request

#13040 Add to blocklist [15]
  src/config.json
Labels: blocklist request

#13049 Add sites to blocklist [24]
  src/config.json
Labels: blocklist request

#13053 Add sites to blocklist [2]
  src/config.json
Labels: blocklist request

#13084 FP "banterbubbles.com",
  src/config.json
Labels: allowlist request

#13089 Fake Uniswap/RevokeCash site phishing for assets
  src/config.json
Labels: blocklist request

#13102 usdtevent.com
  src/config.json
Labels: blocklist request

#13103 Add Sites to Blocklist [6]
  src/config.json
Labels: blocklist request

#13097 Remove metamask/members as codeowner
  .github/CODEOWNERS
Labels: improvement

#13129 Add sites to blocklist [9]
  src/config.json
Labels: blocklist request

#13134 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13132 Block 116 scams. Remove redundant subdomains. Keep relevant apex domains only.
  src/config.json
Labels: blocklist request

#13135 dydxevent.info
  src/config.json
Labels: blocklist request

#13147 Add fake RocketPool phishing site
  src/config.json
Labels: blocklist request

#13151 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13111 blacklist rangos-exchange.com phishing site
  src/config.json
Labels: blocklist request
