Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-04, with the labels that each got.

#12179 Add Phishing Sites to Blocklist [28]
  src/config.json
Labels: blocklist request

#12207 Scams 20230403
  src/config.json
Labels: blocklist request

#12196 Add phishing url to blacklist
  src/config.json
Labels: blocklist request

#12202 Add new phishing domains 4-1-23
  src/config.json
Labels: blocklist request

#12215 add 146 scam urls
  src/config.json
Labels: blocklist request

#12219 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#12224 add optimismfoundations.com
  src/config.json
Labels: blocklist request

#12227 Add heymint.pm to blacklist
  src/config.json
Labels: blocklist request

#12213 adding phishing sites to blocklist [5]
  src/config.json
Labels: blocklist request

#12208 Add Phishing Sites to Blocklist [10]
  src/config.json
Labels: blocklist request

#12232 nakamigos.net
  src/config.json
Labels: blocklist request

#12246 Port master merges
  src/config.json
Labels: blocklist request, confirmed malicious

#12294 Add domains to blocklist [258]
  src/config.json
Labels: blocklist request

#12301 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#12310 add 229 scam urls
  src/config.json
Labels: blocklist request

#12302 Block 106 Scam URLs
  src/config.json
Labels: blocklist request

#12238 [scripts/add-hosts,validate-new-config] Fix redundancy validation
  src/add-hosts.js
  src/validate-new-config.js
Labels: bug, improvement

#12430 Add to blocklist [5]
  src/config.json
Labels: blocklist request
