Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-10, with the labels that each got.

#13712 Adding phishing sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#13722 Adding phishing sites to blocklist [5]
  src/config.json
Labels: blocklist addition

#13727 Block 223 scams
  src/config.json
Labels: blocklist addition

#13723 add sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#13726 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#13743 Update config.json
  src/config.json
Labels: blocklist addition

#13744 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13746 add sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#13748 Add sites to blocklist [9]
  src/config.json
Labels: blocklist addition

#13749 Block 164 scams
  src/config.json
Labels: blocklist addition

#13751 temp - galxe.com
  src/config.json
  test/confirm-blocklist.test.js
Labels: blocklist addition

#13750 Update config.json
  src/config.json
Labels: blocklist addition

#13785 Remove galxe.com from blocklist
  src/config.json
  test/confirm-blocklist.test.js
Labels: blocklist removal

#13788 Block 138 scams
  src/config.json
Labels: blocklist addition

#13770 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#13780 Update config.json
  src/config.json
Labels: blocklist addition

#13800 Removing FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#13791 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13796 Add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#13798 Block 58 scams
  src/config.json
Labels: blocklist addition

#13805 Adding phishing sites to blocklist [16]
  src/config.json
Labels: blocklist addition

#13809 Add sites to blocklist [10]
  src/config.json
Labels: blocklist addition

#13820 Update config.json
  src/config.json
Labels: blocklist addition

#13823 Add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#13834 Block 69 scams, remove FP `1inch.agency`
  src/config.json
Labels: blocklist addition, blocklist removal

#13837 Update config.json
  src/config.json
Labels: blocklist addition

#13833 Update config.json
  src/config.json
Labels: blocklist addition

#13843 Update config.json
  src/config.json
Labels: blocklist addition

#13831 Add sites to blocklist [5]
  src/config.json
Labels: blocklist addition

#13847 Block 340 scams
  src/config.json
Labels: blocklist addition

#13851 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13855 Scams 20231016
  src/config.json
Labels: blocklist addition

#13856 Add scam to BL
  src/config.json
Labels: blocklist addition

#13858 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13861 Adding phishing sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#13862 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13863 Update config.json
  src/config.json
Labels: blocklist addition

#13864 Add sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#13868 Add sites to blocklist [15]
  src/config.json
Labels: blocklist addition

#13871 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13874 Update config.json
  src/config.json
Labels: blocklist addition

#13882 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13879 Add site to blocklist [1]
  src/config.json
Labels: blocklist addition

#13881 Block 105 scams
  src/config.json
Labels: blocklist addition

#13887 Removing FP's from blocklist [3]
  src/config.json
Labels: blocklist removal

#13888 Adding phishing sites to blocklist [4]
  src/config.json
Labels: blocklist addition

#13889 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13892 add free-claiming root domain to blocklist
  src/config.json
Labels: blocklist addition

#13902 Update config.json
  src/config.json
Labels: blocklist addition

#13903 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13905 add free-eigenlayer to blocklist
  src/config.json
Labels: blocklist addition

#13908 Update config.json
  src/config.json
Labels: blocklist addition

#13909 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#13910 Add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#13920 add zora.co to whitelist
  src/config.json
Labels: allowlist addition

#13952 Add sites to blocklist [18]
  src/config.json
Labels: blocklist addition

#13955 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13956 Update config.json
  src/config.json
Labels: blocklist addition

#13957 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13958 Block 152 scams
  src/config.json
Labels: blocklist addition

#13978 Add sites to blocklist [18]
  src/config.json
Labels: blocklist addition

#13997 Add sites to blocklist [7]
  src/config.json
Labels: blocklist addition
