Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-05, with the labels that each got.

#12394 scripts/validate-new-config: display dupe hosts in error output
  src/validate-new-config.js
Labels: improvement

#12451 Add to blocklist [50]
  src/config.json
Labels: blocklist request

#12485 Add sites to blocklist [22]
  src/config.json
Labels: blocklist request

#12490 add back openmeta.network to allowlist
  src/config.json
Labels: allowlist request

#12513 revokemycash.com
  src/config.json
Labels: blocklist request

#12534 Add phishing url to blacklist
  src/config.json
Labels: blocklist request

#12539 Add Phishing Sites to Blocklist [24]
  src/config.json
Labels: blocklist request

#12552 Add to blocklist [5]
  src/config.json
Labels: blocklist request

#12566 adding phishing sites to blocklist [2]
  src/config.json
Labels: blocklist request

#12603 Add phishing sites to blocklist 05/17
  src/config.json
Labels: blocklist request

#12608 Add phishing url to blacklist
  src/config.json
Labels: blocklist request

#12606 Block 175 scam URLs
  src/config.json
Labels: blocklist request

#12629 Add Phishing Sites to Blocklist [29]
  src/config.json
Labels: blocklist request

#12643 Adding phishing site to blocklist [1]
  src/config.json
Labels: blocklist request

#12662 Add Phishing Sites to Blocklist [40]
  src/config.json
Labels: blocklist request

#12667 add opensea phishing links to the blacklist
  src/config.json
Labels: blocklist request

#12691 Scams 20230529
  src/config.json
Labels: blocklist request

#12692 Add Phishing Sites to Blocklist [16]
  src/config.json
Labels: blocklist request

#12715 Block 27 scams
  src/config.json
Labels: blocklist request

#12703 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#12713 add 148 scam urls
  src/config.json
Labels: blocklist request
