Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-03, with the labels that each got.

#11781 Add Phishing Sites to Blocklist [14]
  src/config.json
Labels: blocklist request

#11810 Add Domains to Blocklist [11]
  src/config.json
Labels: blocklist request

#11837 Add new phishing domains
  src/config.json
Labels: blocklist request

#11835 Block Unstoppable domains scam (google ads), OpenSea, Blur, Metamask
  src/config.json
Labels: blocklist request

#11839 Add scams targetting Lido, Optimism, and CollabLand
  src/config.json
Labels: blocklist request

#11846 Add airdrop scam
  src/config.json
Labels: blocklist request

#11854 zksyncs.app
  src/config.json
Labels: blocklist request

#11856 Block 137 scam URLs
  src/config.json
Labels: blocklist request

#11849 Add Phishing Sites to Blocklist [7]
  src/config.json
Labels: blocklist request

#11855 Add new phishing domains
  src/config.json
Labels: blocklist request

#11864 Add Phishing Sites to Blocklist [31]
  src/config.json
Labels: blocklist request

#11872 remove domain from blacklist
  src/config.json
Labels: allowlist request, reviewed for unblocking

#11877 Add Phishing Sites to Blocklist [8]
  src/config.json
Labels: blocklist request

#11885 Add scams targeting Optimism, ZetaChain, and collabland
  src/config.json
Labels: blocklist request

#11888 Add scams targetting Lido
  src/config.json
Labels: blocklist request

#11886 Add claims-digidaigaku.com to blacklist
  src/config.json
Labels: blocklist request

#11889 Update config.json
  src/config.json
Labels: blocklist request

#11894 Add Phishing Sites to Blocklist [15]
  src/config.json
Labels: blocklist request

#11867 Add Domains to Blocklist [1]
  src/config.json
Labels: blocklist request

#11857 Added new phishing domains
  src/config.json
Labels: blocklist request

#11887 Remove Domains from Blocklist [4] Add Domains to Allowlist [1]
  src/config.json
Labels: allowlist request

#11896 Block 104 scam URLs
  src/config.json
Labels: blocklist request

#11909 Add new phishing domains
  src/config.json
Labels: blocklist request

#11904 Block scam URLs
  src/config.json
Labels: blocklist request

#11903 Add new phishing domains
  src/config.json
Labels: blocklist request

#11911 add circle-airdrop[.]org
  src/config.json
Labels: blocklist request

#11912 Add new phishing domains
  src/config.json
Labels: blocklist request

#11913 Add new phishing domains
  src/config.json
Labels: blocklist request

#11916 Block CIRCLE USDC 1:1 redeem scams and others
  src/config.json
Labels: blocklist request

#11918 Add scams targetting Optimism
  src/config.json
Labels: blocklist request

#11834 add 147 scam urls
  src/config.json
Labels: blocklist request

#11843 add phising site
  src/config.json
Labels: blocklist request

#11924 Add scams targetting CoW Protocol
  src/config.json
Labels: blocklist request

#11922 Add new phishing domains
  src/config.json
Labels: blocklist request

#11920 Block 75 Scams Circle USDC 1:1 claims - continued
  src/config.json
Labels: blocklist request

#11921 Add phishing url to blacklist
  src/config.json
Labels: blocklist request

#11932 Add Phishing Sites to Blocklist [17]
  src/config.json
Labels: blocklist request

#11931 Block circle USDC scams (continued...)
  src/config.json
Labels: blocklist request

#11955 Add scams targetting ChainPatrol Automation
  src/config.json
Labels: blocklist request

#11959 Add Phishing Sites to Blocklist [13]
  src/config.json
Labels: blocklist request

#11963 Scams 20230316
  src/config.json
Labels: blocklist request

#11964 Add new phishing domains
  src/config.json
Labels: blocklist request

#11966 Add scams targetting ChainPatrol Automation
  src/config.json
Labels: blocklist request

#11974 Add new phishing domains
  src/config.json
Labels: blocklist request

#11987 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#11985 Site Impersonating Polygon (fixed)
  src/config.json
Labels: blocklist request

#11983 Add new phishing domains
  src/config.json
Labels: blocklist request

#11992 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#11986 add phishing domains to blacklist
  src/config.json
Labels: blocklist request

#11991 Add new phishing domain
  src/config.json
Labels: blocklist request

#11990 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#11958 Add new phishing domains
  src/config.json
Labels: blocklist request

#11965 Add Domains to Blocklist [11]
  src/config.json
Labels: blocklist request

#12023 Add Phishing Sites to Blocklist [20]
  src/config.json
Labels: blocklist request

#12024 Scams 20230321
  src/config.json
Labels: blocklist request

#12019 add scams targeting Arbitrum and Optimism
  src/config.json
Labels: blocklist request

#12006 Add phishing domain to blocklist
  src/config.json
Labels: blocklist request

#12040 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#12056 Main master merge
  src/config.json
Labels: blocklist request

#12057 add phishing domain to blacklist
  src/config.json
Labels: blocklist request

#12051 added-dapp-pro-phishing-domain
  src/config.json
Labels: blocklist request

#12048 Add Phishing Sites to Blocklist [8]
  src/config.json
Labels: blocklist request

#12076 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#12068 Add https://gpt-4-openai.com/
  src/config.json
Labels: blocklist request

#12066 Block 74 Scam URLs
  src/config.json
Labels: blocklist request

#12077 Add scams targetting Arbitrum
  src/config.json
Labels: blocklist request

#12065 Add Phishing Sites to Blocklist [8]
  src/config.json
Labels: blocklist request

#12064 Updated a blacklist for a phishing site.
  src/config.json
Labels: blocklist request

#12014 Add new phishing domains
  src/config.json
Labels: blocklist request

#12010 removing site from blocklist [2] adding to allowlist [2]
  src/config.json
Labels: allowlist request

#11981 Add Phishing Sites to Blocklist [8]
  src/config.json
Labels: blocklist request

#12102 Add new phishing domain
  src/config.json
Labels: blocklist request

#12130 enseth.domains
  src/config.json
Labels: blocklist request

#12134 Add scams targetting Arbitrum
  .gitignore
  src/config.json
Labels: blocklist request

#12142 [chore] update devDependencies
  package.json
  test/index.js
  yarn.lock
Labels: dependencies

#12148 deps: replace fast-levenshtein with fastest-levenshtein
  package.json
  src/detector.js
  yarn.lock
Labels: dependencies

#12147 Add Phishing Sites to Blocklist [16]
  src/config.json
Labels: blocklist request

#12160 add mask-tokens.io to blocklist
  src/config.json
Labels: blocklist request

#12180 scripts/clean-config: fix tolerance check
  src/clean-config.js
Labels: improvement

#12178 test: verify that every fuzzylist entry is also in allowlist
  test/index.js
Labels: improvement
