Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-11, with the labels that each got.

#14019 Update config.json
  src/config.json
Labels: blocklist addition

#14020 Add sites to blocklist [25]
  src/config.json
Labels: blocklist addition

#14021 Block 178 scams
  src/config.json
Labels: blocklist addition

#14016 Removing FP from blocklist [2]
  src/config.json
Labels: blocklist removal

#14022 Update config.json
  src/config.json
Labels: blocklist addition

#14017 adding phishing sites to blocklist [7]
  src/config.json
Labels: blocklist addition

#14023 Rm lidofinance.github.io
  src/config.json
Labels: blocklist removal

#14025 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14027 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14031 Update config.json
  src/config.json
Labels: blocklist addition

#14040 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14047 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14044 Adding phishing domains to blocklist
  src/config.json
Labels: blocklist addition

#14043 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14050 Add sites to blocklist [20]
  src/config.json
Labels: blocklist addition

#14052 Remove False Positive [1]
  src/config.json
Labels: blocklist removal

#14055 Remove False Positive [1]
  src/config.json
Labels: blocklist removal

#14056 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14059 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14063 Block 143 scams
  src/config.json
Labels: blocklist addition

#14060 Update config.json
  src/config.json
Labels: blocklist addition

#14069 Block 38 scams
  src/config.json
Labels: blocklist addition

#14073 Update config.json
  src/config.json
Labels: blocklist addition

#14077 Update config.json
  src/config.json
Labels: blocklist addition

#14079 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14080 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14081 Phishing domains 11 04 23
  src/config.json
Labels: blocklist addition

#14082 add site to blocklist [1]
  src/config.json
Labels: blocklist addition

#14086 Block 106 scams
  src/config.json
Labels: blocklist addition

#14098 Adding phishing sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#14102 Block 198 scams
  src/config.json
Labels: blocklist addition

#14103 Add sites to blocklist [11]
  src/config.json
Labels: blocklist addition

#14105 Scams 20231108
  src/config.json
Labels: blocklist addition

#14106 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14107 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14119 Block 59 scams
  src/config.json
Labels: blocklist addition

#14127 Remove FP's from blocklist [3]
  src/config.json
Labels: blocklist removal

#14128 Adding phishing sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#14140 Add sites to blocklist [18]
  src/config.json
Labels: blocklist addition

#14149 adding phishing sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#14150 Update config.json
  src/config.json
Labels: blocklist addition

#14154 Remove bnbminer.finance from blacklist
  src/config.json
Labels: blocklist removal, fp blocked multiple times

#14155 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14156 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14158 added fake verification site
  src/config.json
Labels: blocklist addition

#14159 Block 98 scams
  src/config.json
Labels: blocklist addition

#14160 Update config.json
  src/config.json
Labels: blocklist addition

#14161 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14163 Scams 20231111
  src/config.json
Labels: blocklist addition

#14170 Update config.json
  src/config.json
Labels: blocklist addition

#14171 Add phishing sites to blocklist - 11/12
  src/config.json
Labels: blocklist addition

#14175 Update config.json
  src/config.json
Labels: blocklist addition

#14179 Update config.json
  src/config.json
Labels: blocklist addition

#14166 add phishing website to the blacklist to config.json
  src/config.json
Labels: blocklist addition

#14172 Remove FPs [3]
  src/config.json
Labels: blocklist removal

#14174 Rm arkinvest-staging.com
  src/config.json
Labels: blocklist removal

#14186 Adding phishing sites to blocklist [4]
  src/config.json
Labels: blocklist addition

#14185 remove false positive nfthunters.cent.co
  src/config.json
Labels: blocklist removal

#14187 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#14191 Add scam websites to blacklist
  src/config.json
Labels: blocklist addition

#14189 Add sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#14199 Update config.json
  src/config.json
Labels: blocklist addition

#14206 Update config.json
  src/config.json
Labels: blocklist addition

#14211 Remove FP's from blocklist [3]
  src/config.json
Labels: blocklist removal

#14210 Add phishing sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#14223 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#14224 Add phishing site to blocklist [1]
  src/config.json
Labels: blocklist addition

#14237 Add phishing sites to blocklist [14]
  src/config.json
Labels: blocklist addition

#14266 add sites to blocklist [5]
  src/config.json
Labels: blocklist addition

#14267 add phishing sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#14269 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14290 remove de.fi
  src/config.json
  test/dapps.json
Labels: blocklist removal

#14349 Update config.json
  src/config.json
Labels: blocklist addition

#14350 Scams 20231128
  src/config.json
Labels: blocklist addition

#14351 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14357 Block 64 drainers by "verified" scam accounts on Twitter/X
  src/config.json
Labels: blocklist addition

#14360 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14366 Phishing domains 11 29 23
  src/config.json
Labels: blocklist addition

#14379 Phishing domains 11 30 23
  src/config.json
Labels: blocklist addition

#14380 Add phishing sites to blocklist [28]
  src/config.json
Labels: blocklist addition
