Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-09, with the labels that each got.

#13420 Add sites to blocklist [21]
  src/config.json
Labels: blocklist request

#13421 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13422 Add phishing sites to blocklist - 8/31
  src/config.json
Labels: blocklist request

#13426 Add phishing sites 09/02
  src/config.json
Labels: blocklist request

#13437 Add phishing sites to blocklist - 09/03
  src/config.json
Labels: blocklist request

#13442 Added 27 new phishing sites
  src/config.json
Labels: blocklist request

#13447 Block 110 scams, remove FPs from issue #13448
  src/config.json
Labels: blocklist request

#13453 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13424 feat: block scam-sniffer.io
  src/config.json
Labels: blocklist request

#13438 Add sites to blocklist [15]
  src/config.json
Labels: blocklist request

#13456 Block 237 scams
  src/config.json
Labels: blocklist request

#13458 Add sites to blocklist [16]
  src/config.json
Labels: blocklist request

#13499 vitalik 2 - consensys digital
  src/config.json
Labels: blocklist request

#13500 consensys network and some others to maybe frontrun
  src/config.json
Labels: blocklist request

#13501 block: consensys.it
  src/config.json
Labels: blocklist request

#13490 Block 157 scams
  src/config.json
Labels: blocklist request

#13489 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13504 Block 27 scams
  src/config.json
Labels: blocklist request

#13508 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13483 add to blocklist [30]
  src/config.json
Labels: blocklist request

#13484 remove fp [3]
  src/config.json
Labels: allowlist request

#13550 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13558 remove false positive [1]
  src/config.json
Labels: allowlist request

#13562 Add scams from ChainPatrol
  src/config.json
Labels: blocklist request

#13573 Adding additional phishing sites using EigenLayer name
  src/config.json
Labels: blocklist addition

#13576 Update Issue Templates
  .github/ISSUE_TEMPLATE/block-domain.md
  .github/ISSUE_TEMPLATE/unblock-domain.md
Labels: improvement

#13579 add sites to blocklist [10]
  src/config.json
Labels: blocklist addition

#13585 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13586 Add phishing sites 09/14
  src/config.json
Labels: blocklist addition

#13587 Add phishing sites to blocklist -- 9/17
  src/config.json
Labels: blocklist addition

#13591 add optimmism.io
  src/config.json
Labels: blocklist addition

#13592 Krisjpi patch 2
  src/config.json
Labels: blocklist addition

#13597 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13599 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13600 Add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#13611 Add sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#13612 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13613 Add two scam websites to blocklist
  src/config.json
Labels: blocklist addition

#13616 Block 39 scams
  src/config.json
Labels: blocklist addition

#13617 add opmainnetwork.io
  src/config.json
Labels: blocklist addition

#13620 Remove balancer.fi
  src/config.json
Labels: blocklist removal

#13622 Adding phishing site to blocklist [1]
  src/config.json
Labels: blocklist addition

#13588 Use third party lists to reduce false positives in blocklist
  .env.example
  .gitignore
  README.md
  package.json
  src/config.json
  test/coinmarketcap.db
  test/confirm-blocklist.test.js
  test/db/.gitkeep
  test/db/coinmarketcaps.txt
  test/db/trancos.txt
  test/index.js
  test/update-static-lists.js
  yarn.lock
Labels: improvement

#13624 add sites to blocklist [13]
  src/config.json
Labels: blocklist addition

#13625 Five More Twitter Phishers
  src/config.json
Labels: blocklist addition

#13629 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#13626 Add phishing sites - 09/21
  src/config.json
Labels: blocklist addition

#13632 freend.xyz scam domain added to blacklist
  src/config.json
Labels: blocklist addition

#13637 Update config.json
  src/config.json
Labels: blocklist addition

#13633 Update config.json: added scam domain thetipcoin.us
  src/config.json
Labels: blocklist addition

#13672 add phishing links from hacked twitter account of dan romero @dwr
  src/config.json
Labels: blocklist addition

#13657 Update config.json
  src/config.json
Labels: blocklist removal
