Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-12, with the labels that each got.

#14383 unblock aerodrome and velodrome
  src/config.json
Labels: blocklist removal

#14411 add phishing sites to blocklist [12]
  src/config.json
Labels: blocklist addition

#14420 Update config.json
  src/config.json
Labels: blocklist addition

#14421 Update config.json
  src/config.json
Labels: blocklist addition

#14424 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14425 Block 264 scams
  src/config.json
Labels: blocklist addition

#14426 Add sites to blocklist [24]
  src/config.json
Labels: blocklist addition

#14430 Scams 20231206
  src/config.json
Labels: blocklist addition

#14436 Scams 20231207
  src/config.json
Labels: blocklist addition

#14438 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14439 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14442 Update config.json
  src/config.json
Labels: blocklist addition

#14447 Update config.json
  src/config.json
Labels: blocklist addition

#14448 Update config.json
  src/config.json
Labels: blocklist addition

#14449 Block 210 scams
  src/config.json
Labels: blocklist addition

#14452 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14462 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14463 Block 28 scams
  src/config.json
Labels: blocklist addition

#14465 Update config.json
  src/config.json
Labels: blocklist addition

#14466 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14469 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14450 Add sites to blocklist [8]
  src/config.json
Labels: blocklist addition

#14467 Block 70 scams
  src/config.json
Labels: blocklist addition

#14470 Update config.json
  src/config.json
Labels: blocklist addition

#14471 Update config.json
  src/config.json
Labels: blocklist addition

#14472 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14473 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14475 Block 49 scams
  src/config.json
Labels: blocklist addition

#14476 add bnbdrop.web3cryp.sbs
  src/config.json
Labels: blocklist addition

#14484 Update config.json
  src/config.json
Labels: blocklist addition

#14485 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14486 Add phishing sites to blocklist - 12/10
  src/config.json
Labels: blocklist addition

#14493 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14494 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14495 Add pudgy scams
  src/config.json
Labels: blocklist addition

#14496 add multiple urls
  src/config.json
Labels: blocklist addition

#14497 add multiple urls base on file match
  src/config.json
Labels: blocklist addition

#14498 add multiple urls basic on file match
  src/config.json
Labels: blocklist addition

#14501 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14492 Remove domains from allowlist
  src/config.json
Labels: allowlist removal

#14502 Block 60 scams
  src/config.json
Labels: blocklist addition

#14503 Update config.json
  src/config.json
Labels: blocklist addition

#14504 Add phising opensea website
  src/config.json
Labels: blocklist addition

#14506 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14509 remove false positive get-verso.com
  src/config.json
Labels: blocklist removal

#14513 add multiple urls base on file match
  src/config.json
Labels: blocklist addition

#14510 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14514 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14511 Update config.json
  src/config.json
Labels: blocklist addition

#14515 Scams 20231213
  src/config.json
Labels: blocklist addition

#14516 Block 40 scams
  src/config.json
Labels: blocklist addition

#14517 Scams 20231213-1 jumping host https://superdreadi.com/readme.html
  src/config.json
Labels: blocklist addition

#14518 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14520 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14521 Phishing domains 12 13 23
  src/config.json
Labels: blocklist addition

#14522 Block 76 scams
  src/config.json
Labels: blocklist addition

#14523 Update config.json
  src/config.json
Labels: blocklist addition

#14525 Scams 20231214
  src/config.json
Labels: blocklist addition

#14526 Update config.json
  src/config.json
Labels: blocklist addition

#14527 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14529 Block 60 scams
  src/config.json
Labels: blocklist addition

#14519 blocklist removal [3]
  src/config.json
Labels: blocklist removal

#14530 add multiple urls
  src/config.json
Labels: blocklist addition

#14531 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14528 Add phishing domains from AngelDrainer phishing team
  src/config.json
Labels: blocklist addition

#14534 Update config.json
  src/config.json
Labels: blocklist addition, allowlist removal

#14536 Scams 20231215
  src/config.json
Labels: blocklist addition

#14538 Block 181 scams
  src/config.json
Labels: blocklist addition

#14539 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14541 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14567 Allowlist revoke.cash
  src/config.json
Labels: allowlist addition

#14568 Added logic to explicitly skip an allowlist redundancy check
  src/add-hosts.js
Labels: enhancement

#14563 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14542 Add opensea phishing websites
  src/config.json
Labels: blocklist addition

#14543 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14546 Added Scam URLs to the blacklist.
  src/config.json
Labels: blocklist addition

#14559 Add sites to blocklist [15]
  src/config.json
Labels: blocklist addition

#14552 Blacklist phishing site - tredarsjoexyz.com
  src/config.json
Labels: blocklist addition

#14564 Remove false positives from blacklist
  src/config.json
Labels: blocklist removal, reviewed for unblocking

#14558 Update config.json
  src/config.json
Labels: blocklist addition

#14570 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14573 False positive removal `app.getresponse.com` - fixes #14571 #14572
  src/config.json
Labels: blocklist removal

#14574 Block 140 scams
  src/config.json
Labels: blocklist addition

#14575 Add phishing sites to blocklist - 12/19
  src/config.json
Labels: blocklist addition

#14576 Blacklisted 2 more links.
  src/config.json
Labels: blocklist addition

#14578 Add phishing url to blacklist
  src/config.json
Labels: blocklist addition

#14579 Block bebopscan
  src/config.json
Labels: blocklist addition

#14580 add sites to blocklist [4]
  src/config.json
Labels: blocklist addition

#14581 remove fp from blocklist [1]
  src/config.json
Labels: blocklist removal

#14588 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14586 Block 61 scams
  src/config.json
Labels: blocklist addition

#14587 Scams 20231220
  src/config.json
Labels: blocklist addition

#14582 Update config.json
  src/config.json
Labels: blocklist addition

#14583 Update config.json
  src/config.json
Labels: blocklist addition

#14589 Add phishing sites to blocklist - 12/20
  src/config.json
Labels: blocklist addition

#14590 add bip32 net to blocklist
  src/config.json
Labels: blocklist addition

#14591 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14592 Update config.json
  src/config.json
Labels: blocklist addition

#14593 Add sites to blocklist [20]
  src/config.json
Labels: blocklist addition

#14595 Add phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14596 Block 100 scams
  src/config.json
Labels: blocklist addition

#14599 remove fp [3]
  src/config.json
Labels: blocklist removal

#14604 Add sites to blocklist [14]
  src/config.json
Labels: blocklist addition

#14608 Add phishing sites to blocklist - 12/22
  src/config.json
Labels: blocklist addition

#14609 remove fp [1]
  src/config.json
Labels: blocklist removal

#14650 Add sites to blocklist [19]
  src/config.json
Labels: blocklist addition

#14669 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14675 compound-labs.xyz
  src/config.json
Labels: blocklist addition

#14672 Block 94 scams
  src/config.json
Labels: blocklist addition

#14656 Update config.json: scam airdrop-manta.network
  src/config.json
Labels: blocklist addition

#14664 Add phishing sites to blocklist - 12/27
  src/config.json
Labels: blocklist addition

#14670 Update config.json
  src/config.json
Labels: blocklist addition

#14673 add openseagifts.vercel.app
  src/config.json
Labels: blocklist addition

#14677 Update config.json
  src/config.json
Labels: blocklist addition

#14681 Update config.json
  src/config.json
Labels: blocklist addition

#14684 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition
