Repository MetaMask/eth-phishing-detect, pull requests merged in 2023-02, with the labels that each got.

#11346 Add scams targetting Lido
  src/config.json
Labels: denylist request

#11355 Scams 20230131
  src/config.json
Labels: denylist request

#11362 Add phishing urls to blacklist
  src/config.json
Labels: denylist request

#11363 Site impersonating Polygon
  src/config.json
Labels: denylist request

#10158 add-hosts: omit redundant hosts from result
  src/add-hosts.js
Labels: enhancement, improvement

#11369 Add scams targetting squishiverse
  src/config.json
Labels: denylist request

#11370 add 124 scam urls
  src/config.json
Labels: denylist request

#11372 Block 76 Scam URLs
  src/config.json
Labels: denylist request

#11379 sites impersonating polygon
  src/config.json
Labels: denylist request

#11386 Add Domains to Blocklist [1]
  src/config.json
Labels: denylist request

#11387 Add Domains to Allowlist [4] & Remove Domains from Blocklist [4]
  src/config.json
Labels: allowlist request

#11394 add 89 scam urls
  src/config.json
Labels: denylist request

#11414 add malicious eth_sign sites
  src/config.json
Labels: denylist request

#11421 add gemv2[.]xyz to blacklist
  src/config.json
Labels: denylist request

#11417 Add Domains to Blocklist [22]
  src/config.json
Labels: denylist request

#11418 Remove Domains from Blocklist [5] Add Domains to Allowlist [14]
  src/config.json
Labels: allowlist request

#11416 Add phishing domains to blocklist
  src/config.json
Labels: denylist request

#11435 Add scams targetting Optimism
  src/config.json
Labels: denylist request

#11449 Scams 20230206
  src/config.json
Labels: denylist request

#11450 Add new phishing domains
  src/config.json
Labels: denylist request

#11448 Sites Impersonating Polygon
  src/config.json
Labels: denylist request

#11462 Add Phishing Sites to Blocklist [13]
  src/config.json
Labels: denylist request

#11518 Add Domains to Blocklist [10]
  src/config.json
Labels: denylist request

#11516 Add scams targetting Optimism
  src/config.json
Labels: denylist request

#11509 Add scams targetting Bored Ape Yach Club Dookey Dash
  src/config.json
Labels: denylist request

#11513 Block 53 Scam URLs
  src/config.json
Labels: denylist request

#11533 Add new phishing domain
  src/config.json
Labels: denylist request

#11512 Add scams targeting Aptos
  src/config.json
Labels: denylist request

#11505 Update config.json to block pudgy-tanks.xyz
  src/config.json
Labels: denylist request

#11536 Add scams targetting Optimism
  src/config.json
Labels: denylist request

#11506 Add Domains to Blocklist [21]
  src/config.json
Labels: denylist request

#11546 Add Phishing Sites to Blocklist [15]
  src/config.json
Labels: denylist request

#11548 adding "vww-opensea.com" to blocklist [1]
  src/config.json
Labels: denylist request

#11550 Add new phishing domains
  src/config.json
Labels: denylist request

#11575 Add Domains to Blocklist [10]
  src/config.json
Labels: denylist request

#11578 Add Phishing Sites to Blocklist [21]
  src/config.json
Labels: denylist request

#11597 Add Phishing Sites to Blocklist [14]
  src/config.json
Labels: denylist request

#11607 Add scams targeting RTFKT
  src/config.json
Labels: denylist request

#11608 Add scams targetting Sappy Seals
  src/config.json
Labels: denylist request

#11609 Add Domains to Blocklist [18]
  src/config.json
Labels: denylist request

#11664 apecoin.is
  src/config.json
Labels: denylist request

#11681 Same as 11672, just re raised
  src/config.json
Labels: denylist request

#11684 Block fake mee6 bot and others
  src/config.json
Labels: denylist request

#11686 Add Domains to Blocklist [24]
  src/config.json
Labels: denylist request

#11729 Scams 20230227
  src/config.json
Labels: blocklist request

#11722 Add scams targetting Lido
  src/config.json
Labels: blocklist request

#11731 Add scams targetting KlimaDAO
  src/config.json
Labels: blocklist request

#11711 add 5 fake arbitrum token sale sites to blocklist
  src/config.json
Labels: blocklist request
