Repository MetaMask/eth-phishing-detect, pull requests merged in 2024-03, with the labels that each got.

#26583 Another set of scams
  src/config.json
Labels: blocklist addition

#26600 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#27135 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#17808 Automatically dedupe blocklist on push to main
  .github/workflows/auto-cleanup.yml
  src/clean-config.js
  test/config.test.js
Labels: improvement

#19273 Fix Fuzzy List Tolerance in add-hosts
  src/add-hosts.js
Labels: improvement

#28053 Add individuals to gate changes to code resources
  .github/CODEOWNERS
Labels: enhancement

#28459 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#28599 Added phishing websites
  src/config.json
Labels: blocklist addition, needs more information

#29747 Add sites to blocklist [5]
  src/config.json
Labels: blocklist addition

#29755 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#29765 Removing FP's [2]
  src/config.json
Labels: blocklist removal

#29767 Adding phishing sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#29774 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#29775 add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#29822 Remove FP "1inch-app.org",
  src/config.json
Labels: blocklist removal

#29862 Scams 20240320
  src/config.json
Labels: blocklist addition

#29874 Removing 2 FP's adding 1 phishing site.
  src/config.json
Labels: blocklist addition, blocklist removal

#29932 brave airdrop scam
  src/config.json
Labels: blocklist addition

#29933 Update config with drainer site
  src/config.json
Labels: blocklist addition
