Repository MetaMask/eth-phishing-detect, pull requests merged in 2024-01, with the labels that each got.

#14709 Add sites to blocklist [28]
  src/config.json
Labels: blocklist addition

#14689 Adding Phishing sites from PRs [5]
  src/config.json
Labels: blocklist addition

#14720 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14730 add galaxyex to blacklist
  src/config.json
Labels: blocklist addition

#14714 Update config.json
  src/config.json
Labels: blocklist addition

#14725 Update config.json
  src/config.json
Labels: blocklist addition

#14726 Phishing domains 01 02 24
  src/config.json
Labels: blocklist addition

#14739 Adding phishing sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#14740 Add phishing sites to blocklist - 1/3
  src/config.json
Labels: blocklist addition

#14741 Add TD phishing sites
  src/config.json
Labels: blocklist addition

#14744 Block fake $mask airdrop tokens and other scams
  src/config.json
Labels: blocklist addition

#14746 Removin FP's from blocklist [4]
  src/config.json
Labels: blocklist removal

#14748 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14758 Update config.json - fake blender site
  src/config.json
Labels: blocklist addition

#14766 Add sites to blocklist [16]
  src/config.json
Labels: blocklist addition

#14767 add paralleltcg and meritcircle phishing sites to blocklist
  src/config.json
Labels: blocklist addition

#14760 Update config.json - SRP phishing sites
  src/config.json
Labels: blocklist addition

#14764 Add phishing sites to blocklist - 1/3
  src/config.json
Labels: blocklist addition

#14770 Scams 20240104
  src/config.json
Labels: blocklist addition

#14777 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#14778 Adding phishing sites to blocklist [7]
  src/config.json
Labels: blocklist addition

#14802 Update config.json
  src/config.json
Labels: blocklist addition

#14807 Add meta phish
  src/config.json
Labels: blocklist addition

#14811 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14745 feature: optimize tests
  src/clean-config.js
  src/config.json
  test/config.test.js
  test/test.util.js
Labels: improvement

#14858 Remove FP [4]
  src/config.json
Labels: blocklist removal

#14863 Adding phishing sites to blocklist [4]
  src/config.json
Labels: blocklist addition

#14864 Block 67 scams
  src/config.json
Labels: blocklist addition

#14868 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14869 adding base domain for phishing sites and removing subdomains [1]
  src/config.json
Labels: blocklist addition

#14881 Block 29 scams
  src/config.json
Labels: blocklist addition

#14899 Removing FP's from blocklist [1]
  src/config.json
Labels: blocklist removal

#14902 Adding phishing sites to blocklist [11]
  src/config.json
Labels: blocklist addition

#14910 Remove uni.live
  src/config.json
Labels: blocklist removal

#14919 Adding phishing sites to blocklist [8]
  src/config.json
Labels: blocklist addition

#14920 Removing FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#14930 retract aptostournament.com
  src/config.json
Labels: blocklist removal

#14928 Scams 20240111
  src/config.json
Labels: blocklist addition

#14937 Add sites to blocklist [47]
  src/config.json
Labels: blocklist addition

#14956 Remove FP's from blocklist [2]
  src/config.json
Labels: blocklist removal

#14957 Adding phishing sites to blocklist [12]
  src/config.json
Labels: blocklist addition

#14958 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14959 Add sites to blocklist [ 4 ]
  src/config.json
Labels: blocklist addition

#14991 add registrar-optimsm.com
  src/config.json
Labels: blocklist addition

#14988 add reward-optimism.io
  src/config.json
Labels: blocklist addition

#14963 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14967 Block 40 scams
  src/config.json
Labels: blocklist addition

#14960 add sites to blocklist [6]
  src/config.json
Labels: blocklist addition

#14973 Update config.json
  src/config.json
Labels: blocklist addition

#14984 add clicksopenboxnft.vercel.app
  src/config.json
Labels: blocklist addition

#14982 Update config.json
  src/config.json
Labels: blocklist addition

#14964 Add sites to blocklist [ 8 ]
  src/config.json
Labels: blocklist addition

#14985 Update config.json
  src/config.json
Labels: blocklist addition, needs more information

#15026 Removing FP's from blocklist [4]
  src/config.json
Labels: blocklist removal

#15027 Add phishing sites to blocklist [19]
  src/config.json
Labels: blocklist addition

#15024 Phishing domains 01 16 24
  src/config.json
Labels: blocklist addition

#15030 Add sites to blocklist [28]
  src/config.json
Labels: blocklist addition

#15046 migrator-rocketpool.net
  src/config.json
Labels: blocklist addition

#15031 Block 83 scams
  src/config.json
Labels: blocklist addition

#15041 Update config.json
  src/config.json
Labels: blocklist addition

#15057 Add domains to blocklist [4]
  src/config.json
Labels: blocklist addition

#15055 block synapse phishing
  src/config.json
Labels: blocklist addition

#15058 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#15076 Adding phishing sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#15105 add phishing site to blocklist [1]
  src/config.json
Labels: blocklist addition

#15107 Removing FP's from blocklist [2]
  src/config.json
Labels: blocklist removal

#15117 Update config.json
  src/config.json
Labels: blocklist addition

#15118 Add sites to blocklist [3]
  src/config.json
Labels: blocklist addition

#15124 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#15194 Remove FP [1]
  src/config.json
Labels: blocklist removal

#15198 Adding phishing site to blocklist [3]
  src/config.json
Labels: blocklist addition

#15213 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#15228 Add phishing sites to blocklist - 01/22
  src/config.json
Labels: blocklist addition

#15234 Add sites to blocklist [ 7 ]
  src/config.json
Labels: blocklist addition

#15242 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#15245 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#15273 Scams 202410124
  src/config.json
Labels: blocklist addition

#15278 add listing-item.io to the blacklist
  src/config.json
Labels: blocklist addition

#15290 Remove re-activated domains being abused from allowlist [3]
  src/config.json
Labels: allowlist removal

#15299 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#15300 Update config.json
  src/config.json
Labels: blocklist addition

#15301 Add sites to blocklist [ 10 ]
  src/config.json
Labels: blocklist addition

#15303 Add citydao[.]click as phishing site
  src/config.json
Labels: blocklist addition

#15304 Add phishing sites to blocklist - 01/24 - 5
  src/config.json
Labels: blocklist addition

#15306 Add phishing sites to blocklist - 01/24 - 6
  src/config.json
Labels: blocklist addition

#15307 Add phishing sites to blocklist - 01/24 - 7
  src/config.json
Labels: blocklist addition

#15308 Add phishing sites to blocklist - 01/24 - 8
  src/config.json
Labels: blocklist addition

#15309 Add phishing sites to blocklist - 01/25
  src/config.json
Labels: blocklist addition

#15339 Add sites to blocklist [1]
  src/config.json
  test/dapps.json
Labels: blocklist addition

#15345 Add phishing sites to blocklist - 01/26
  src/config.json
Labels: blocklist addition

#15348 Gemini phishing sites that are targeting web3 wallets as of 2023-01-26.
  src/config.json
Labels: blocklist addition

#15353 Add sites to blocklist [ 15 ]
  src/config.json
Labels: blocklist addition

#15359 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#15363 add sites to blocklist [29]
  src/config.json
Labels: blocklist addition

#15383 Block 40 scams
  src/config.json
Labels: blocklist addition

#15420 Add phishing sites to blocklist - 01/27
  src/config.json
Labels: blocklist addition

#15421 add karatdao.fi
  src/config.json
Labels: blocklist addition

#15444 Adding phishing sites to blocklist [9]
  src/config.json
Labels: blocklist addition

#15448 Remove FP's from blocklist [2]
  src/config.json
Labels: blocklist removal

#15455 Remove pandoshi.com from blocklist
  src/config.json
Labels: blocklist removal

#15445 Add sites to blocklist [ 15 ]
  src/config.json
Labels: blocklist addition

#15454 Update config.json
  src/config.json
Labels: blocklist addition, needs more information

#15456 Add site to blocklist [1]
  src/config.json
Labels: blocklist addition

#15508 Add sites to blocklist [2]
  src/config.json
Labels: blocklist addition

#15511 Remove FPs from blocklist [2] and weird dupe [1]
  src/config.json
Labels: blocklist removal

#15529 adding phishing sites to blocklist [67]
  src/config.json
Labels: blocklist addition

#15530 add fees-etherscan.com to the blocklist
  src/config.json
Labels: blocklist addition

#15580 Add sites to blocklist [ 6 ]
  src/config.json
Labels: blocklist addition

#15581 Adding "bitcoinminetrix.com"
  src/config.json
Labels: blocklist addition

#15583 Update config.json
  src/config.json
Labels: blocklist addition

#15602 Removing FP from blocklist [1]
  src/config.json
Labels: blocklist removal
