Repository MetaMask/eth-phishing-detect, pull requests merged in 2024-02, with the labels that each got.

#15661 Add phishing sites to blocklist [27]
  src/config.json
Labels: blocklist addition

#15668 Adding phishing sites to blocklist [30]
  src/config.json
Labels: blocklist addition

#15730 add en-opensea.io to the blocklist
  src/config.json
Labels: blocklist addition

#16297 remove domain from allowlist [1]
  src/config.json
Labels: allowlist removal

#16791 Remove fp: puffer.fi
  src/config.json
Labels: blocklist removal

#12288 Update README.md
  README.md
Labels: improvement

#14905 Optimize tests a little more
  .github/workflows/build-test.yml
  src/compare-git-configs.sh
  src/validate-new-config.js
Labels: improvement

#16848 Adding phosphor.xyz to allowlist
  src/config.json
Labels: allowlist addition

#16849 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#14535 Snaps Registry DB for Allowlist
  README.md
  package.json
  test/confirm-blocklist.test.js
  test/db/coinmarketcaps.txt
  test/db/snapsregistry.txt
  test/update-static-lists.js
Labels: improvement, allowlist addition

#17563 Remove FP from blocklist [1]
  src/config.json
Labels: blocklist removal

#18274 Clear out stale allowlist entries
  src/config.json
Labels: allowlist removal

#18324 Clean the allowlist some more, sort the fuzzylist
  src/config.json
Labels: allowlist removal

#17903 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#18041 Add sites to blocklist [ 14 ]
  src/config.json
Labels: blocklist addition

#19585 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#19970 Remove False Positive finceptor.app
  src/config.json
Labels: blocklist removal

#19946 Add scams from ChainPatrol
  src/config.json
Labels: blocklist addition

#21851 Remove FP [1]
  src/config.json
Labels: blocklist removal

#25808 batch blocklist prs
  src/config.json
Labels: blocklist addition

#25815 batch prs
  src/config.json
Labels: blocklist addition

#25829 batch prs
  src/config.json
Labels: blocklist addition
